### ISSUE TITLE
Extra effects

### ISSUE THREAD

**Issue by yaxu** [musikinformatik/SuperDirt#100]
More effects to include as default?
* https://github.com/datamads/SpectralTricks from @datamads
* https://github.com/calumgunn/TidalFX from @calumgunn

**Comment by calumgunn** [comment]
I can probably get PRs in for TidalFX this weekend :)

**Comment by bgold-cosmos** [comment]
I have a few too, I'll try to get them polished up ASAP.

**Comment by yaxu** [comment]
ping @madskjeldgaard, any interest? :)

**Comment by madskjeldgaard** [comment]
Yes! Go ahead!

**Comment by madskjeldgaard** [comment]
I can do a PR if you prefer

**Comment by yaxu** [comment]
@madskjeldgaard that'd be perfect I reckon

**Comment by madskjeldgaard** [comment]
Do we put them in `default-effects-extra.scd` ?

**Comment by telephon** [comment]
@madskjeldgaard yes, why not!

**Comment by madskjeldgaard** [comment]
okay I'm almost done with this (+ adding new fx!) but where do I put/what do I do with the tidal params? @yaxu

**Comment by madskjeldgaard** [comment]
Ah nevermind, I see I can just add them in the tidal repo. Cool!

**Comment by madskjeldgaard** [comment]
done
