### ISSUE TITLE
SuperDirt for just MIDI

### ISSUE THREAD

**Issue by ovitus** [musikinformatik/SuperDirt#105]
So I'm using SuperDirt as per these instructions:
http://blog.tidalcycles.org/superdirt-midi/

I'm not using the audio synthesis, just MIDI. SuperDirt takes hold of JACK and I can't run my VST in ALSA mode, or play youtube instructional videos while it is running. Is there a way to prevent it from attaching to any audio device so it works solely for MIDI?

**Comment by telephon** [comment]
Try to quit the server: `s.quit`. Does that help? You could also just not start the server.

**Comment by ovitus** [comment]
If I don't start the SuperDirt server, when I evaluate:
~dirt.soundLibrary.addMIDI(\midi, ~midiOut);

I get:
ERROR: Message 'soundLibrary' not understood.
RECEIVER:
   nil
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = nil
		arg selector = 'soundLibrary'
		arg args = [*0]
	< closed FunctionDef >  (no arguments or variables)
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "~dirt.soundLibrary.addMIDI(\..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'soundLibrary' not understood.
RECEIVER: nil

**Comment by telephon** [comment]
I didn't mean that you should not make a `SuperDirt` instance in the startup file. I meant that you just skip the lines that boot the server. But I noticed that this will throw some errors. Better you just quit the server after startup, e.g.:

`~dirt.server.quit`.

Of course it would be better to fix the other issue, maybe you can post it on the supercollider issue tracker?

**Comment by telephon** [comment]
please do feel free to reopen if you have more questions

**Comment by StijnGovaere** [comment]
Hi!
I get the same error message "'soundLibrary' not understood"
SuperDirt v1.1.3
SC 3.10
Tidal 1.5.2

SuperDirt.start;
MIDIClient.init;
~midiOut = MIDIOut.newByName("IAC Driver", "Bus 1");
~midiOut.latency = 0;
~dirt.soundLibrary.addMIDI(\midi, ~midiOut);
--> ERROR: Message 'soundLibrary' not understood.

I recompiled Class Library, rebooted SC several times but can't seem to get it work..

Thanks

**Comment by yaxu** [comment]
You'll be on an old version of superdirt @StijnGovaere

**Comment by StijnGovaere** [comment]
Hi Alex. Do you mean I probably have 2 versions of SuperDirt? I installed v1.1.3 but should have deleted the older version first?
I'll try that
Thanks

**Comment by StijnGovaere** [comment]
Hi again,
I've deleted and reinstalled SuperDirt (1.1.3) several times now but keep have the same error.
No matter which version I install, the Readme file says it's v1.0dev.

Is there an other way to check which version I installed? 

Thanks for your help!

**Comment by StijnGovaere** [comment]
tried this also and still no luck :(

Quarks.checkForUpdates({Quarks.install("SuperDirt", "v1.1.3"); thisProcess.recompile()})

**Comment by StijnGovaere** [comment]
Server.killAll; saved my day..!

Thanks & Sorry for the newbie questions...

Server.killAll;
Quarks.checkForUpdates({Quarks.install("SuperDirt", "v1.1.3"); thisProcess.recompile()});
SuperDirt.start;
MIDIClient.init;
~midiOut = MIDIOut.newByName("IAC Driver", "Bus 1");
~midiOut.latency = 0;
~dirt.soundLibrary.addMIDI(\midi, ~midiOut);

--------------
SuperDirt: listening to Tidal on port 57120
MIDI Sources:
	MIDIEndPoint("IAC Driver", "Bus 1")
MIDI Destinations:
	MIDIEndPoint("IAC Driver", "Bus 1")
-> MIDIClient
-> a MIDIOut
-> a MIDIOut
-> a DirtSoundLibrary

**Comment by telephon** [comment]
I've added a method that one can call in such cases, hope it saves some time for some:

```
SuperDirt.resetEverything
```

**Comment by StijnGovaere** [comment]
Great! Thanks.
