### ISSUE TITLE
Ctrl-dot

### ISSUE THREAD

**Issue by yaxu** [musikinformatik/SuperDirt#107]
It'd be good to be able to do the equivalent of ctrl-dot from tidal, to silence running synths

Maybe by diverting the `ctrldot` sample name, e.g. via `once $ s "ctrldot"`

**Comment by telephon** [comment]
You can add it yourself:

```supercollider
~dirt.soundLibrary.addSynth(\ctrldot, (play: { CmdPeriod.run }));
```

if this is useful, we can add it to the startup somewhere.

**Comment by telephon** [comment]
In order to just silence running synths and not stop everything that is running in sclang, you could also write 

```supercollider
~dirt.soundLibrary.addSynth(\ctrldot, (play: { ~dirt.orbits.do(_.freeSynths) }));
```

**Comment by yaxu** [comment]
Ok how about calling it 'superpanic' `~dirt.soundLibrary.addSynth(\superpanic, (play: { ~dirt.orbits.do(_.freeSynths) }));`
