### ISSUE TITLE
DirtPause causes first event after pause to be dropped

### ISSUE THREAD

**Issue by bgold-cosmos** [musikinformatik/SuperDirt#109]
This is much easier to test with things like `asap` or "momentary" transitions.

If the output has been silent long enough for DirtPause in the monitor to kick in, then the first event that should unpause things doesn't actually produce sound.  For example (using the new transition):

```
tidal> onceFor 1 1 $ n (run 4) # s "alphabet"
[ hear "a" "b" "c" "d" ]
[ wait over eight seconds ]
tidal> onceFor 1 1 $ n  (run 4) # s "alphabet"
[ hear "b" "c" "d" ]
```

I've checked the OSC messages using "Server Dump OSC", and Tidal is sending them, but that first one doesn't get played.

Commenting out the DirtPause line in dirt_monitor fixes the issue, but doesn't seem like a great idea due to the extra CPU load.  I've tried rearranging other things but haven't been able to find a fix.

I believe this has been affecting the global effects too, they often seem to take an event to "kick in" properly.

**Comment by telephon** [comment]
ah, that should really not happen indeed.

reproducer in sclang:
```supercollider
SuperDirt.default = ~dirt;
(type:\dirt, s: \alphabet).play; // doesn't work the first time.
```

**Comment by telephon** [comment]
@bgold-cosmos want to try?

**Comment by bgold-cosmos** [comment]
Seems to work - I'm waiting until after toplap15 to test thoroughly... 
I thought I'd tried something like that but I think I was messing with the \resumed instead  🤦‍♂️

**Comment by telephon** [comment]
great that you found the culprit so well! It is a bit a strange error, and the fix is a bit of guesswork on my side. There are asynchronous (or hard to specify) things happening sometimes with releases and inits in envelopes, and audio rate is more timing accurate. Maybe it points to an issue with `TrigControl` in supercollider.

The solution is a little less efficient, but it' not a big difference.

**Comment by telephon** [comment]
feel free to reopen!

**Comment by telephon** [comment]
>Maybe it points to an issue with `TrigControl` in supercollider.

no, seems to work correctly:

```supercollider
(
OSCdef(\x, { "trigger received".postln }, '/reply');
a = { var t = \trig.tr(0); SendReply.kr(t) }.play;
)

s.sendBundle(0.2, ["/n_run", a.nodeID, 0 ]);

(
s.sendBundle(0.2, 
	["/n_run", a.nodeID, 1 ],
	["/n_set", a.nodeID, "trig", 1]
)
)

// => trigger received
```
