### ISSUE TITLE
SuperDirt LATEST isn't the latest

### ISSUE THREAD

**Issue by yaxu** [musikinformatik/SuperDirt#111]
When I install the LATEST version via Quarks.gui, I get this:

```
alex@stanage:~/.local/share/SuperCollider/downloaded-quarks/SuperDirt$ git status
HEAD detached at aa9deba
nothing to commit, working tree clean
```

In other words the 'LATEST' version is from a year ago:
  https://github.com/musikinformatik/SuperDirt/commit/aa9deba

I can't work out why..

**Comment by yaxu** [comment]
Ah, that is the last commit to make it to 'master':
  https://github.com/musikinformatik/SuperDirt/tree/master

As a quick fix (because this is confusing people), I'll do a pull from develop to master.

**Comment by telephon** [comment]
I've opened an issue, let's see: https://github.com/supercollider/supercollider/issues/4321

**Comment by yaxu** [comment]
But maybe the current situation is what we want.. otherwise by default, people will install the develop branch..

**Comment by telephon** [comment]
yes, true.

**Comment by yaxu** [comment]
For now I updated the tidal install instructions to the following, to avoid hitting #114
```
Quarks.checkForUpdates(); Quarks.install("SuperDirt", "v1.0")
```

**Comment by telephon** [comment]
with "v1.0" you'll now get an older one.

**Comment by yaxu** [comment]
I just ran
`Quarks.checkForUpdates(); Quarks.install("SuperDirt", "v1.1.1");`
and got
`WARNING: Tag not found: Quark: SuperDirt[v1.1.1] v1.1.1`

then I ran the lines separately, and it found and installed v1.1.1 fine

I'm not sure if supercollider is just ignoring the first command, or whether the second command is run before the first one completes.. Would love a working one-liner though, any ideas? I guess `thisProcess.recompile` on the end would be good too

**Comment by yaxu** [comment]
This seems to do the trick:
`Quarks.checkForUpdates({Quarks.install("SuperDirt", "v1.1.1"); thisProcess.recompile()})`

**Comment by telephon** [comment]
ah, ok, synchronisation …

**Comment by yaxu** [comment]
I think the release process we have now works well.
