### ISSUE TITLE
SynthDef dirt_gate1 not found

### ISSUE THREAD

**Issue by yaxu** [musikinformatik/SuperDirt#114]
Develop and master are both broken, it seems, throwing this error for every trigger:

> *** ERROR: SynthDef dirt_gate1 not found
>FAILURE IN SERVER /s_new SynthDef not found

**Comment by telephon** [comment]
I'll take a look.

**Comment by telephon** [comment]
It seems as if on startup the synthdefs are not laoded.

**Comment by telephon** [comment]
Somewhere, later than init time, `~numChannels` is set to `1`, while it should be `2`.

**Comment by telephon** [comment]
ok, found it.

**Comment by telephon** [comment]
@yaxu can test it and cherry-pick it onto master?

**Comment by yaxu** [comment]
Thanks!

**Comment by telephon** [comment]
well, my bad …
