### ISSUE TITLE
"scheduler queue is full" while working with SuperDirt MIDI

### ISSUE THREAD

**Issue by OscarSouth** [musikinformatik/SuperDirt#123]
While working in TidalCycles and sending SuperDirt MIDI data out, my SuperDirt instance is giving me pages and pages of this message:

```
scheduler queue is full.
scheduler queue is full.
scheduler queue is full.
```

I am actually noticing missing MIDI data today, although this is the first time in a long time that I've noticed that. I'm going to restart my laptop in a bit and see if that continues.

I've played around with the numbers in my startup file and haven't noticed any tangible differences. Is there any suggested course of action to take to remedy this?

Cheers,
Oscar

**Comment by OscarSouth** [comment]
Quick an additional note -- I'm getting floods of these messages even when I'm not sending any data from tidal (for example, if I name `something = d1 $ {somecode}` without running it, the messages will already be appearing. They don't seem to be causing any tangible effects on performance and don't start until the Atom plugin (which is what I'm using for tidal) is booted.

**Comment by yaxu** [comment]
Hmm, I think booting tidal wouldn't normally have any effect on superdirt. Do you have something like a midi clock in your tidal boot script?

**Comment by telephon** [comment]
what version of supercollider are you on?

**Comment by telephon** [comment]
You could try this branch and let me know if that is any better: https://github.com/musikinformatik/SuperDirt/tree/topic-test-midi-queue

**Comment by OscarSouth** [comment]
Hey, apologies for the delay in addressing this -- while prepping for Algomech I've had my hardware and software versions 'frozen' and have been working around non-critical problems rather than trying to fix them (I'd prefer to know what can go wrong and how to avoid it, than not know what might go wrong -- takes a little time to build that intuition so I 'freeze' my devices a few months before any given concert).

That said, I have been running the version on the branch that you suggested previously. I don't find any issues in behaviour (I can push tidal HARD for hours on end with no issues whatsoever) but the `scheduler queue is full.` spam is still occurring:

```
oscarsouth@OS-AVL:~$ sclang -v
sclang 3.10.2 (Built from branch 'develop' [63783aeca])
```

**Comment by telephon** [comment]
What is the sclang config code for the midi message sending?

**Comment by ovitus** [comment]
I'm having this same issue, with a flood of "scheduler queue is full." messages with SuperDirt MIDI. I have 3 midi ports open:
~midiOut1 = MIDIOut.newByName("Midi Through", "Midi Through Port-0");                                                                          
~midiOut2 = MIDIOut.newByName("Midi Through", "Midi Through Port-1");                                                                          
~midiOut3 = MIDIOut.newByName("Midi Through", "Midi Through Port-2"); 

I'm pushing things fairly hard in Tidal along with VSTs loaded in Reaper. I think it may be messing up note scheduling. Is there something I can tweak to try and improve performance, or is it hardware related?

**Comment by telephon** [comment]
I assume you are using `scripts/tidal-midi.scd`? If yes, could you take a look in `DirtEventTypes`, in the definition of `midiEvent` there is this part:

```supercollider
if(latency == 0.0) {
	midiout.performList(midicmd, args)
} {
	thisThread.clock.sched(latency, {
		midiout.performList(midicmd, args);
	})
};
if(hasGate and: { midicmd === \noteOn }) {
	thisThread.clock.sched(sustain + latency, {
		midiout.noteOff(*args)
	});
}
```

Try to check which branch it is using, by adding e.g. a `"hello".postln` there:

```supercollider
if(latency == 0.0) {
	"hello".postln;
	midiout.performList(midicmd, args)
} {
	"hello I am here".postln;
	thisThread.clock.sched(latency, {
		midiout.performList(midicmd, args);
	})
};
if(hasGate and: { midicmd === \noteOn }) {
	"no I am here!".postln;
	thisThread.clock.sched(sustain + latency, {
		midiout.noteOff(*args)
	});
}
```
(you have to recompile the class library (cmd-L) after the change.

Then we'll know in which direction to go next.

**Comment by telephon** [comment]
feel free to reopen.
