### ISSUE TITLE
Increase default number of orbits

### ISSUE THREAD

**Issue by yaxu** [musikinformatik/SuperDirt#134]
I think 10 (number of fingers) or 12 (most divisible low number) would be better than the current default number of orbits, which I think is 2, but my guess at where the default is set is here, and it seems to be 1:
 https://github.com/musikinformatik/SuperDirt/blob/dd378ea88b014b3e20dbe4bf77138c0eadbe06ce/classes/SuperDirt.sc#L40

I'm not sure whether we should change any default memory requirements etc to match.

When this is done I'll change the tidal default boot to send different channels to the different orbits via:
```
    d1 = p 1 . (|< orbit 0) 
    d2 = p 2 . (|< orbit 1) 
    d3 = p 3 . (|< orbit 2) 
```
I think new users will find this behaviour less surprising when it comes to using global effects.

**Comment by telephon** [comment]
OK. We will have to spend a bit of electricity for each orbit, not too much though. Why is it necessary?

**Comment by yaxu** [comment]
@telephon so you don't have the cognitive load of having to think about putting reverb etc on a different orbit

**Comment by telephon** [comment]
makes sense now.

**Comment by yaxu** [comment]
When starting with `SuperDirt.start`, the default number of orbits still seems to be two. I tagged a new release thinking the old one was out of date, but I still get `WARNING: SuperDirt: event falls out of existining orbits`.
