### ISSUE TITLE
load sample folder with a different name

### ISSUE THREAD

**Issue by ovitus** [musikinformatik/SuperDirt#140]
I would like to load a folder of samples with a particular name, similar to how you can load an individual file and specify a name:

Like this for one specific sample:
~dirt.loadSoundFile("/home/samples/07038105.wav", "1");

This doesn't work, but was wondering if there was something that did:
~dirt.loadSoundFiles("/home/samples/sa808/34*", "test");

**Comment by telephon** [comment]
`loadSoundFileFolder`?
