### ISSUE TITLE
Message 'sanitize' not understood when starting SuperDirt

### ISSUE THREAD

**Issue by valentinlageard** [musikinformatik/SuperDirt#143]
Hi, when launching SuperDirt, the following error shows up :
`ERROR: Message 'sanitize' not understood.`

Here is the detailed error message : https://gist.github.com/valentinlageard/de8471bc1013dce7d870e04620319ba8

I tried to reinstall SuperDirt with latest version but it didn't solve the problem...

**Comment by bgold-cosmos** [comment]
It could be that your SuperCollider itself is a bit out of date, do you know what version you're running?
_____________________
Ben Gold
bgold.cosmos@gmail.com
(651) 706-4789

**Comment by valentinlageard** [comment]
Yup, 3.8.0.
Also I tried removing Superdirt/synth/try-load-extra-synths.scd and it works so the error comes from here. If I'm understanding correctly, it loads sc3 plugins so maybe the problem comes from there ?

**Comment by bgold-cosmos** [comment]
It's the "sanitize" method that one of the synths there uses - apparently it didn't exist until SuperCollider 3.9.0
_____________________
Ben Gold
bgold.cosmos@gmail.com
(651) 706-4789
