### ISSUE TITLE
Timestretching?

### ISSUE THREAD

**Issue by yaxu** [musikinformatik/SuperDirt#146]
Ref https://github.com/tidalcycles/Tidal/issues/554 , is there a quick way to add timestretching to superdirt, so e.g. samples can be played higher without getting shorter?

**Comment by bgold-cosmos** [comment]
Timestretching tends to sound terrible unless you use a quite sophisticated method; I've experimented a little in SuperCollider but have never gotten very good results.  Doing a little Googling suggests there might be a way to implement a WSOLA algorithm in there (someone has probably already done it).  I'll keep looking.

**Comment by bgold-cosmos** [comment]
[AREUREEEADY.zip](https://github.com/musikinformatik/SuperDirt/files/3658447/AREUREEEADY.zip)

Two problems so far
  * It may not be fast enough for realtime.  My test code is in Python, though, so it might be OK when translated to SuperCollider
  * The actual amount of stretch is different from the requested because it tries to do some wavelet similarity matching, so it's really hard to control the duration of the output with this method

There may be some variations I can try, though, this is fun stuff...

**Comment by yaxu** [comment]
That sounds good to me, nice one!

**Comment by telephon** [comment]
yes, I'm sure it would make a good plugin! You may have to design it in a way that it conforms to the scsynth way (very very little memory allocation at startup of the ugen).

**Comment by bgold-cosmos** [comment]
Example implementation in #149 

I couldn't get any of the wavelet similarity stuff to work well for all samples, so fell back to a fairly simple overlap-add method.  The nice part about this is no extra memory allocation is needed, and the whole thing can be done by just making some custom phase inputs to BufRd and summing over them.

**Comment by yaxu** [comment]
I saw there is a new(?) time stretch quark: https://github.com/spluta/TimeStretch
It would still be great to get https://github.com/musikinformatik/SuperDirt/pull/229 merged, as a flavourful stretch!

**Comment by yaxu** [comment]
Ah now I look, I see that that timestretch quark isn't realtime.

**Comment by telephon** [comment]
> It would still be great to get #229 merged, as a flavourful stretch!

Yes, I've just made a comment, it is not fully resolved yet, but not far away.

**Comment by aptrn** [comment]
Any update on this? 
Seems like #229 has been merged but the wordy counterpart is not yet implemented in Tidal?

Totally my most wanted feature 🥇

**Comment by telephon** [comment]
I has already been merged :)

**Comment by ndr-brt** [comment]
@aptrn you just need to define the timescale parameter:
```let timescale = pF "timescale"```

then you can use with your samples, like:
```d1 $ s "cp" # timestretch 5```

**Comment by yaxu** [comment]
We still need to add the parameters to tidal. @bgold-cosmos is it `timescale` and `timescalewin` that we want? Does it make sense to use these parameters with control buses?

**Comment by yaxu** [comment]
I tried it, and they don't work with control buses - just went silent when I tried with timescalebus.. So added them to the 'nobus' list.
