### ISSUE TITLE
setting sustain for external soft synth ADSR envelope

### ISSUE THREAD

**Issue by ovitus** [musikinformatik/SuperDirt#147]
I'm using TidalCycles/SuperCollider/SuperDirt to send MIDI to Reaper to play notes on U-he Diva. If I set the sustain too low, it truncates the note duration without allowing the synths ADSR envelope to shape the sound completely. Is there a specific number to use to bypass this parameter or should it just be set to a high enough number for the ADSR to get a full length note? Any downsides to setting it too high?

**Comment by telephon** [comment]
The `sustain` parameter in Tidal/SuperDirt is the total duration of the sound. Maybe this is the problem? It seems more a question of how you set up your synths on U-he Diva, no?

**Comment by msp** [comment]
Note also that changing the pattern speed (via `fast` or `slow`) will automatically adjust the `sustain` value unless you explicitly set it.

**Comment by ovitus** [comment]
oh didn't know that, thanks
