### ISSUE TITLE
adjusting note velocity

### ISSUE THREAD

**Issue by ovitus** [musikinformatik/SuperDirt#148]
I think this is also a SuperDirt question:

for MIDI, setting any value for velocity (0, 1, 127) doesn't sound like it has any affect on the sound?
I've been getting into sequencing VCV to make use of this synth: https://mutable-instruments.net/modules/elements/ and wanted to have velocity control a VCA-like input

I think gain = velocity for superdirt midi, but it's strange, 0.38 seems to be maximum velocity, gradually decreasing with higher values

**Comment by telephon** [comment]
Yes, gain and velocity are the same. This is taken from the the MIDI implementation of supercollider. You use the `amp` parameter in tidal, and this should have the full range.
