### ISSUE TITLE
SuperDirt fails to load on SuperCollider - Windows 10

### ISSUE THREAD

**Issue by abhirajdg** [musikinformatik/SuperDirt#172]
I have been trying to install SuperCollider and TidalCycles on my machine. When I do a 

> SuperDirt.start

I get the following error:

> *** Welcome to SuperCollider 3.10.3. *** For help press Ctrl-D.
> Booting server 'localhost' on address 127.0.0.1:57110.
> SCDoc: Indexing help-files...
> 
> Device options:
>   - MME : Microsoft Sound Mapper - Input   (device #0 with 2 ins 0 outs)
>   - MME : Microphone Array (2- Realtek(R)   (device #1 with 2 ins 0 outs)
>   - MME : Stereo Mix (2- Realtek(R) Audio   (device #2 with 2 ins 0 outs)
>   - MME : Microsoft Sound Mapper - Output   (device #3 with 0 ins 2 outs)
>   - MME : Speaker / Headphone (2- Realtek   (device #4 with 0 ins 2 outs)
>   - Windows DirectSound : Primary Sound Capture Driver   (device #5 with 2 ins 0 outs)
>   - Windows DirectSound : Microphone Array (2- Realtek(R) Audio)   (device #6 with 2 ins 0 outs)
>   - Windows DirectSound : Stereo Mix (2- Realtek(R) Audio)   (device #7 with 2 ins 0 outs)
>   - Windows DirectSound : Primary Sound Driver   (device #8 with 0 ins 2 outs)
>   - Windows DirectSound : Speaker / Headphone (2- Realtek(R) Audio)   (device #9 with 0 ins 2 outs)
>   - ASIO : ASIO4ALL v2   (device #10 with 2 ins 2 outs)
>   - Windows WASAPI : Speaker / Headphone (2- Realtek(R) Audio)   (device #11 with 0 ins 2 outs)
>   - Windows WASAPI : Stereo Mix (2- Realtek(R) Audio)   (device #12 with 2 ins 0 outs)
>   - Windows WASAPI : Microphone Array (2- Realtek(R) Audio)   (device #13 with 2 ins 0 outs)
>   - Windows WDM-KS : Stereo Mix (Realtek HD Audio Stereo input)   (device #14 with 2 ins 0 outs)
>   - Windows WDM-KS : Microphone Array (Realtek HD Audio Mic input)   (device #15 with 2 ins 0 outs)
>   - Windows WDM-KS : Speakers (Realtek HD Audio output)   (device #16 with 0 ins 2 outs)
> 
> Requested devices:
>   In (matching device NOT found):
>   - (null)
>   Out (matching device NOT found):
>   - (null)
> 
> Selecting default system input/output devices
> 
> Booting with:
>   In: MME : Microphone Array (2- Realtek(R)
>   Out: MME : Speaker / Headphone (2- Realtek
> SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Unanticipated host error'
> could not initialize audio.
> SCDoc: Indexed 1363 documents in 1.59 seconds
> Server 'localhost' exited with exit code -1073740791.

Can anyone help me out with a solution here?

**Comment by telephon** [comment]
instead of doing `SuperDirt.start`, could you please try a `s.boot`? If the error is the same, it is not specific SuperDirt error. Then please ask on the sc-users mailing list or add an issue at the SuperCollider repository: https://github.com/supercollider/supercollider 

Thanks!

**Comment by abhirajdg** [comment]
Thanks for the quick reply. Did that, here's the error I get:

> Booting server 'localhost' on address 127.0.0.1:57110.
> 
> Device options:
>   - MME : Microsoft Sound Mapper - Input   (device #0 with 2 ins 0 outs)
>   - MME : Microphone Array (2- Realtek(R)   (device #1 with 2 ins 0 outs)
>   - MME : Stereo Mix (2- Realtek(R) Audio   (device #2 with 2 ins 0 outs)
>   - MME : Microsoft Sound Mapper - Output   (device #3 with 0 ins 2 outs)
>   - MME : Speaker / Headphone (2- Realtek   (device #4 with 0 ins 2 outs)
>   - Windows DirectSound : Primary Sound Capture Driver   (device #5 with 2 ins 0 outs)
>   - Windows DirectSound : Microphone Array (2- Realtek(R) Audio)   (device #6 with 2 ins 0 outs)
>   - Windows DirectSound : Stereo Mix (2- Realtek(R) Audio)   (device #7 with 2 ins 0 outs)
>   - Windows DirectSound : Primary Sound Driver   (device #8 with 0 ins 2 outs)
>   - Windows DirectSound : Speaker / Headphone (2- Realtek(R) Audio)   (device #9 with 0 ins 2 outs)
>   - ASIO : ASIO4ALL v2   (device #10 with 2 ins 2 outs)
>   - Windows WASAPI : Speaker / Headphone (2- Realtek(R) Audio)   (device #11 with 0 ins 2 outs)
>   - Windows WASAPI : Stereo Mix (2- Realtek(R) Audio)   (device #12 with 2 ins 0 outs)
>   - Windows WASAPI : Microphone Array (2- Realtek(R) Audio)   (device #13 with 2 ins 0 outs)
>   - Windows WDM-KS : Stereo Mix (Realtek HD Audio Stereo input)   (device #14 with 2 ins 0 outs)
>   - Windows WDM-KS : Microphone Array (Realtek HD Audio Mic input)   (device #15 with 2 ins 0 outs)
>   - Windows WDM-KS : Speakers (Realtek HD Audio output)   (device #16 with 0 ins 2 outs)
> 
> Requested devices:
>   In (matching device NOT found):
>   - (null)
>   Out (matching device NOT found):
>   - (null)
> 
> Selecting default system input/output devices
> 
> Booting with:
>   In: MME : Microphone Array (2- Realtek(R)
>   Out: MME : Speaker / Headphone (2- Realtek
> SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Unanticipated host error'
> could not initialize audio.
> Server 'localhost' exited with exit code -1073740791.

Seems like the same issue to me.

**Comment by telephon** [comment]
… so please try in the other repository, OK?

**Comment by telephon** [comment]
For discussion and solution see: https://github.com/supercollider/supercollider/issues/4718
