### ISSUE TITLE
Default settings too conservative?

### ISSUE THREAD

**Issue by yaxu** [musikinformatik/SuperDirt#176]
Quite often someone will have an issue with numBuffers, memSize, or maxNodes being too low. I haven't checked if SuperDirt sets these or whether it's the supercollider defaults, but out of the box, things work for some people, and not others.
Should we just get superdirt to set them higher as part of the startup?

Relatedly, for a memory allocation error, SC errors point the end user here: http://supercollider.sourceforge.net/wiki/index.php/User_FAQ 

However this wiki page currently doesn't give enough error for a superdirt beginner to solve the problem, as they won't know what their server name is.

**Comment by telephon** [comment]
perhaps as a first step we should add an `s.quit` to the startup. If someone has the server running already, the higher settings we add for the server options won't be updated until it is rebooted.
