### ISSUE TITLE
WARNING: SuperDirt: event falls out of existing orbits, index (4)

### ISSUE THREAD

**Issue by ovitus** [musikinformatik/SuperDirt#193]
Not sure what this is, I'm seeing this in the output of SuperCollider:

WARNING: SuperDirt: event falls out of existing orbits, index (4)
WARNING: SuperDirt: event falls out of existing orbits, index (5)

**Comment by telephon** [comment]
You may have started superdirt with just 2 orbits, e.g., and you have something like `# orbit 5` in your code. SuperDirt will wrap, but also warn. If you don't want to be warned, you can also switch it off: `~dirt.warnOutOfOrbit = false`. But probably you want more orbits at initialisation time?

**Comment by yaxu** [comment]
Further to that, the default startup now runs 12 orbits, so this indicates that you're running an out of date superdirt (which you can upgrade to "LATEST" via `Quarks.gui`), or have a custom startup that needs updating.

**Comment by ovitus** [comment]
I had configured 4 orbits to save on system resources since I wasn't using them all. Doing that caused channels d5 and above to result in this error. I think my system can handle the 12 orbits so I'll just set it to that or switch the warning off if it can't. Thanks

**Comment by yaxu** [comment]
You can edit your boottidal.hs file to change how d1 etc map to orbits
