### ISSUE TITLE
default-effects-extra missing from default install?

### ISSUE THREAD

**Issue by jwaldmann** [musikinformatik/SuperDirt#194]
Hi. I have supercollider (3.11.0) and sc3-plugins (git master). I installed SuperDirt with
`Quarks.install("SuperDirt")`.  

None of the effects in `defaults-effects-extra` seem to be working when  I call them from Tidal (1.4.9). E.g., `xsdelay`, `comb`, `triode` are accepted in Tidal code, but do not change the sound, and `sclang` shows no error.

The file `default-effects-extra.scd` is not mentioned in `sclang`'s messages
```
...
shared memory server interface initialized
loading synthdefs in /home/waldmann/.local/share/SuperCollider/downloaded-quarks/SuperDirt/classes/../synths/core-modules.scd
---- core synth defs loaded ----
loading synthdefs in /home/waldmann/.local/share/SuperCollider/downloaded-quarks/SuperDirt/classes/../synths/core-synths.scd
loading synthdefs in /home/waldmann/.local/share/SuperCollider/downloaded-quarks/SuperDirt/classes/../synths/default-synths.scd
loading synthdefs in /home/waldmann/.local/share/SuperCollider/downloaded-quarks/SuperDirt/classes/../synths/try-load-extra-synths.scd
loading synthdefs in /home/waldmann/.local/share/SuperCollider/downloaded-quarks/SuperDirt/classes/../synths/tutorial-synths.scd

loading 216 sample banks:
...
```

**Comment by telephon** [comment]
Hm, this is strange, maybe an sc3-plugins issue …  Is the problem still there?

**Comment by jwaldmann** [comment]
Seems to work now (with SC 3.12.2-rc1, cf. https://github.com/supercollider/supercollider/issues/5678) 

I still don't know what xsdelay does, but it does something...
