### ISSUE TITLE
Defining a mixed channel for the speakers while recording multichannel audio

### ISSUE THREAD

**Issue by tugrulsalci** [musikinformatik/SuperDirt#195]
I am using TidalCycles and while I am recording multichannel audio on SuperCollider; I don't hear any audio after third channel even the output file has all the channels. Because audio device in Windows allows 3 channel most. Would it be possible to mix all the channels for the speaker output and still being able to record the multichannel audio? Please note that I know very little about supercollider and superdirt languages/interfaces.

**Comment by telephon** [comment]
There is no very simple way, because the simple way is normally just to record the output busses you are playing through.

**Comment by telephon** [comment]
But you could check out the recorder here:

https://github.com/musikinformatik/SuperDirt/blob/develop/hacks/chunk-recorder.scd

Maybe that helps?

**Comment by telephon** [comment]
@tugrulsalci please reopen this issue if you have more questions – it seems more like a documentation issue.
