### ISSUE TITLE
Fixed a small bug in the pitchshifting SynthDef and add a parameter

### ISSUE THREAD

**Issue by thgrund** [musikinformatik/SuperDirt#205]
I have seen that there is a "dirt_pitch_shift" module in core_synths. Unfortunately it does not work as intended, because the pitch shift parameter "pitchRatio" in core_synths is called ``psratio`` and in core_modules ``psrate``. 
I fixed this typo (now it is called `psrate` everywhere) and was able to use it successfully on the tidal side.

I also added the timeDispersion parameter for PitchShift and named it `disp`.

Link to PR: 
https://github.com/musikinformatik/SuperDirt/pull/206

At this point a short question (since I don't know where else to ask it): Should I rather always create an issue (like this one), even if I have "only" small changes to suggest?

**Comment by yaxu** [comment]
Thanks for this. I guess if you already have a PR, there's no big reason to create an issue as well? I don't have a strong opinion though!
