### ISSUE TITLE
SuperDirt fails to start on Windows 10

### ISSUE THREAD

**Issue by johnpmayer** [musikinformatik/SuperDirt#22]
Running `include("SuperDirt")` seems to work fine

Running `SuperDirt.start` consistently throws the below. Rebooting the interpreter has not effect

```
*** Welcome to SuperCollider 3.7.2. *** For help press Ctrl-D.
booting 57110
-> SuperDirt
Exception in World_New: boost::interprocess::intermodule_singleton initialization failed
RESULT = -1073740791
ERROR: server failed to start
For advice: [http://supercollider.sf.net/wiki/index.php/ERROR:_server_failed_to_start]
```

My specs
- Windows 10
- SuperCollider 3.7.2

**Comment by telephon** [comment]
Does SuperCollider  3.7.2 start the server without superdirt?

**Comment by johnpmayer** [comment]
Huh, unable to repro. Rebooting or something must have taken care of it. Maybe a orphan process holding the port.
