### ISSUE TITLE
strange behavior, seemingly `cut` related

### ISSUE THREAD

**Issue by bgold-cosmos** [musikinformatik/SuperDirt#23]
Originally raised by kindohm on Slack, I've tried to reduce it to the most minimal example I can find using stock samples and explore what's going on.  With 0.8 Tidal and SuperDirt, try the following code in Tidal:

```
d1
  $ stut 8 0.2 0.1
  $ jux (iter 8)
  $ stack[
    s "supersaw([3 5 3 2]/4,8)" # cut "1" # sustain "0.5",
    s "d*4 drum*2" # n (run 30),
    s "super808*8" # sustain "0.1"
  ]

hush

d1 $ sound "superpwm/2"

hush
```

Let the first (long) pattern play for a while... at some point I hear an audible glitch.  Hush playback, and evaluate the second pattern.  On stock 0.8 Tidal and SuperDirt I then hear a bunch of other sounds playing whenever the "superpwm" is triggered.  This behavior lasts until SuperDirt is rebooted.

The `cut` parameter seems to be critical, I haven't found any odd behavior without it.  Also the added-on `stut` and `iter` seem to be important too, I haven't managed to reproduce the behavior without those lines.

My _guess_ is that something odd happens when too many events arrive to SuperDirt trying to `cut` each other simultaneously.  It seems to also happen when non-sample-based synths using `cut` are combined with both samples and non-sample-based synths without `cut`, but that's been tricky to investigate.

**Comment by telephon** [comment]
Maybe related, not sure however: https://github.com/supercollider/supercollider/issues/1023 (this should be solved, but we need to check again)

**Comment by telephon** [comment]
<img width="461" alt="screen shot 2016-06-12 at 10 30 32" src="https://cloud.githubusercontent.com/assets/1810559/15990011/bcc0d0fc-3088-11e6-858d-073a5967fdc3.png">

I can see them notes hanging.

**Comment by telephon** [comment]
There are late messages:

```
late 0.010788266
late 0.010735883
late 0.010735845
late 0.010733483
late 0.010732480
late 0.001842619
late 0.001831511
late 0.001830923
late 0.001831313
```

**Comment by telephon** [comment]
tidal sends with too little latency, here is the listing of some:

```
070049390356871
0.069807463369216
0.06942249435815
0.069218800359522
0.069025707358378
0.081352531458833
0.081143084462383
0.08086014946457
0.080521077470621
0.080111971459701
0.079742071466171
0.091895110730547
0.091440420728759
0.09111642872449
0.090621445735451
0.090416585735511
0.090235005729483
0.10257263499079
0.10238947499602
0.10223691198917
0.10197761400195
0.1017777609959
0.10158892899926
late 0.002465023
late 0.002464853
0.034072531459969
0.03336559147283
0.045615358729265
0.04541689773032
0.055963153994526
0.055295528989518
0.067378596257186
0.066940744261956
```

**Comment by telephon** [comment]
in `Dirt.hs`, the latency is defined as: `latency = 0.04`. This may be too short.

**Comment by telephon** [comment]
hm, changing it, I don't get late messages anymore, but still hanging notes. false track.

**Comment by bgold-cosmos** [comment]
OK, I don't quite get what's going on underneath the hood here, but I was messing around with the  `dirt_gate` SynthDef and changed both those `doneAction`s to `5` (from `3`).  And this _seems_ to fix the problem without breaking anything else.  Does this make sense at all?

**Comment by telephon** [comment]
very interesting, yes it a way it kind of makes sense. Certainly precisely the right spot to look at. The general problem about done actions is that apart from 0 and 2 they are very little used by programmers. So I could imagine that `3` has a bug that `5` doesn't have, or that the documentation is ambiguous.

**Comment by telephon** [comment]
please feel free to reopen if necessary.
