### ISSUE TITLE
Adding global effect examples in hack folder doesn't work properly

### ISSUE THREAD

**Issue by fracnesco** [musikinformatik/SuperDirt#231]
The example doesn't work properly, for a reference on how to add global effect see
https://github.com/ndr-brt/sc-adente/blob/master/synths/mutable.scd#L227 
from line 227
https://github.com/ndr-brt/sc-adente/blob/master/superdirt_startup.scd#L31
from line 31 to 39

**Comment by telephon** [comment]
Thank you, I'll take a look in a little while!
