### ISSUE TITLE
Control the envelope of # cut

### ISSUE THREAD

**Issue by cephasteom** [musikinformatik/SuperDirt#237]
When I use `cut` in Tidal to truncate samples when another one plays, I often get clicks and pops. This is especially apparent on subby samples such as longer kick drums. For an example of the artefacts that arise, run
```
d1 $ s "wobble*8" # cut 1
```
In the example above I could, of course, just shorten the envelope of the notes, but I don't always know in advance how long each note will be and I want to able to sustain notes indefinitely until the next note is played and cuts off the previous one.

Is there a way of controlling the envelope of the cut event? I'm assuming the click occurs because the sample is released too abruptly. Is is possible to control the release time of the cut event?

Many thanks.

**Comment by telephon** [comment]
Have you tried to set the `#fadeInTime` or `# fadeTime` parameters? Defaults are very short (`0.001`), you can set them to e.g. `0.03` and see if it gets better.

**Comment by cephasteom** [comment]
Hi @telephon - thanks so much for getting back to me so quickly, and on a Sunday too! `# fadeTime` appears to do the job although I have to add it as a parameter in Tidal, e.g. `let fadeTime = pI "fadeTime"`. That's brilliant and has solved an issue that's been annoying me for a while. I'll close this issue now. Best wishes... Pete.

**Comment by yaxu** [comment]
Ah I have these in a list of parameters that can't be controlled via buses, but am not actually exposing them. So:

* fadeTime - fade out time. So I could make a `fadeOutTime` alias in tidal
* fadeInTime - Only used if begin > 0

Is that right?

I also have `length` and `endSpeed`, but these seem internal to the calculation of begin`/`end and `accelerate` respectively, and don't seem to do anything if I send values from tidal.

**Comment by yaxu** [comment]
Added the fades https://github.com/tidalcycles/Tidal/commit/681ecee4635f8b26c68eecfbbb0b19c24ace2cb8

**Comment by telephon** [comment]
>Is that right?

yes!

>endSpeed

we could expose it, at a little bit of cost.

**Comment by yaxu** [comment]
@petethomasmusique you'll want to use `pF` rather than `pI` there by the way
