### ISSUE TITLE
Accelerate question

### ISSUE THREAD

**Issue by bgold-cosmos** [musikinformatik/SuperDirt#24]
Why is the accelerate parameter exponential?  I have a patch to modify it to a linear speed change (like in classic Dirt), but I don't know whether to submit a PR since I don't understand the reason for it.

**Comment by telephon** [comment]
It was just a guess, and essentially waited for comments. By default, I make time related parameters exponential. But acceleration is a borderline case.

What sounds better?

**Comment by bgold-cosmos** [comment]
For my purposes I switched it to `endSpeed = speed * (1.0 + accelerate);`, although now that I look at classic Dirt's code I think technically it effectively does `endSpeed = speed + (accelerate * dur);`.

Both produce linear speed changes over time (which IMO sounds better), the only real difference is whether to scale with speed and/or duration.

**Comment by telephon** [comment]
OK that makes sense, acceleration is already the derivative. Scaling with duration would mean scaling with the effective sample duration (= the sustain)? I think it might be better controllable with your first variant.

**Comment by telephon** [comment]
can you make a PR for 0.9-dev?

**Comment by bgold-cosmos** [comment]
Will do - one thing I also did was remove the restriction on flipping the sign of speed.  I haven't noticed any negative effects from this but I should test it a little (or put it back) first.

**Comment by telephon** [comment]
Ah yes, just saw your comment here. Let's see.

**Comment by ndr-brt** [comment]
I would ask why the restriction of flipping the sign of speed was removed. I think it's useful to avoid unexpected behaviour.
e.g.
```
d1 $ s "sine" # accelerate (-2)
```

that should produce a tight kick, it produces a weird sound with an ending click.
Any possibility to reintroduce the `if the sign of end speed is different from the speed one, set at 0` control?

**Comment by ndr-brt** [comment]
Ok, noticed that it's enough setting accelerate to "-1" and playing with sustain parameter to achieve what I need.

**Comment by telephon** [comment]
I don't understand, sorry.  If you want a slow down,  you set `accelerate` to `1/100` e.g.
```
endSpeed = speed * (1.0 + accelerate);
```

**Comment by ndr-brt** [comment]
with `accelerate = 1/100` the final speed will be almost the same, so it won't slow down.
to slow down, the accelerate value should be `< 0` but, as it's implemented, with values `< -1` the endSpeed sign will be different from the speed sign, so in the playing there will be a down+up behaviour.

But, as I said, that's ok, the behaviour I wanted could be obtained setting accelerate to "-1" and sustain to a value smaller than 1

**Comment by telephon** [comment]
Ah yes, I see, makes sense.

Just make sure to note that `sustain` is simply the absolute duration of the sample. It should have no connection with speed.
