### ISSUE TITLE
SuperDirt runs twice

### ISSUE THREAD

**Issue by yaxu** [musikinformatik/SuperDirt#245]
I've seen this problem a couple of times and think it might be quite common.. It happens when people make a custom startup based on https://github.com/musikinformatik/SuperDirt/blob/develop/superdirt_startup.scd , but don't realise that they shouldn't run `SuperDirt.start` as well -- so they end up with two superdirts and all events duplicated. This runs fine but with some confusing issues (samples not found by one of the processes, but they still are heard because the one with the custom startup has them loaded), as well as performance and memory issues.

When this confusion is cleared up, of course everything sounds thinner and quieter without the unintentional chorus effect.. Hmm!

Anyway, maybe superdirt should detect itself already running and resist being loaded more than once.

**Comment by telephon** [comment]
we could add a global effect `thicken` :)
