### ISSUE TITLE
[Question] does superdirt support SFZ?

### ISSUE THREAD

**Issue by MushiTheMoshi** [musikinformatik/SuperDirt#250]
Hi all . First of all thank you so much for the work done here, is awesome and I have had hours of fun with it. Well just wondering if superdirt supports SFZ files ? I couldn't find anything in the documentation ... just want to confirm ... 

Thanks,
Julio

**Comment by telephon** [comment]
SuperDirt uses [libsndfile](http://www.mega-nerd.com/libsndfile/), I don't think SFZ (sound fonts) are supported by it but I didn't do any further query.

**Comment by MushiTheMoshi** [comment]
thank you
