### ISSUE TITLE
sc3-plugins: Why?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [musikinformatik/SuperDirt#253]
I tried to install Tidal on NixOS a couple years ago and couldn't, because I couldn't install sc3-plugins. I'm not sure what the README said before, but now it says that sc3-plugins is only "recommended". What will I be missing if I don't have it?

**Comment by yaxu** [comment]
Hi @JeffreyBenjaminBrown, I think you would be missing almost all the synths, and some of the effects, live reverb (room/size). I'd call it 'highly recommended'. There is a bit of history around core supercollider vs sc3-plugins, as far as I can tell sc3-plugins is a bit messy in a way that is difficult to clean up.

**Comment by JeffreyBenjaminBrown** [comment]
Aha! Thanks, Alex.

Those reasons seem worth putting in the README, no?
