### ISSUE TITLE
Release version numbering is inconsistent, breaking automated version checking

### ISSUE THREAD

**Issue by cleary** [musikinformatik/SuperDirt#258]
Hi guys, 
I finally got around to checking my [ansible installer](https://github.com/cleary/ansible-tidalcycles) against the new superdirt release.

I use the following command which relies on getting the latest release number at the bottom of the list of tagged releases:
```
git ls-remote https://github.com/musikinformatik/SuperDirt.git | grep tags | tail -n1 | awk -F/ '{print $NF}'
...
b60e9b9fdf9c752e07d7581313f9ad99f6e3e98b        refs/tags/1.1.1
59d5f80fbc926110bbd1b93e08b12c17a051a9c5        refs/tags/v.1.7.3
85e10518539cc559542d3051eb87323e7b968fe9        refs/tags/v1.0
69514a476e4372bfab6bf432180c3bc4dc5da837        refs/tags/v1.1
b60e9b9fdf9c752e07d7581313f9ad99f6e3e98b        refs/tags/v1.1.1
9f139ae162595334b437fb73ca33f90ccf784fb2        refs/tags/v1.1.2
439960c38a47c73aa0a83f5c5077f8ec1ae52cb2        refs/tags/v1.1.3
4f4adc9b07c255108d146695038c5e83dce9292d        refs/tags/v1.7
c2ad95e1c77ca5e4b2fb5d913c8e0acfc9c78261        refs/tags/v1.7.1
7abb62e89649daa1232b9cbd6427241868abd30e        refs/tags/v1.7.2
```

As you can see, the 1.7.3 release broke the standard (sitting way back in the list), and subsequently my installer fails to update to 1.7.3.

Are you able to re-release (or re-tag) so it's consistent with previous releases?

**Comment by telephon** [comment]
@alex et al, should we make a new release?

**Comment by cleary** [comment]
I'm unsure how the quarks in supercollider work for referencing specific versions, but if they use git tags would it be enough just to add a `v1.7.3` tag at the same commit as `v.1.7.3` without further work?
 
It just occurred to me that this version inconsistency also presents a problem for any documentation referencing the `v1.7.2` format tag - people will be applying (and potentially updating documentation) the increment incorrectly in their configs.

**Comment by yaxu** [comment]
Oops sorry for this typo! I was able to edit the existing release to fix the tag. Hopefully that's enough?

**Comment by cleary** [comment]
oops, wasn't logged in - was wondering why I couldn't reply :P

that's done the trick.
