### ISSUE TITLE
`arp` step patterns not working

### ISSUE THREAD

**Issue by Git-Christopher** [musikinformatik/SuperDirt#264]
`n (arp "up" "c'maj7'8")` works but `n (arp "up" "c'maj7'[8]")` does not -- when the step argument is placed within square brackets for patterning, it does not produce eight steps and the notes produced do not relate to the chord that is defined.

**Comment by telephon** [comment]
seems to be something on the tidal side, perhaps?

**Comment by Git-Christopher** [comment]
i'm so sorry, wrong directory! moving to tidal issues!

**Comment by telephon** [comment]
thanks!
