### ISSUE TITLE
delay stops working sometimes

### ISSUE THREAD

**Issue by ahihi** [musikinformatik/SuperDirt#270]
every now and then after i've been iterating on a pattern for a while, the `dirt_delay` on that orbit goes silent and stops responding to any arguments from tidal. not sure what exactly triggers it.

this is the first variant of `dirt_delay` which uses `SwitchDelay` when sc3-plugins is installed. i noticed that unlike others, this synth runs two pausing ugens ([1](https://github.com/musikinformatik/SuperDirt/blob/ab76e795826b3e91e13c519eae3f97dacc6397f8/synths/core-synths-global.scd#L92), [2](https://github.com/musikinformatik/SuperDirt/blob/ab76e795826b3e91e13c519eae3f97dacc6397f8/synths/core-synths-global.scd#L99)) with one even having a comment saying it doesn't work properly. i don't understand the effect synth lifecycle well but this seems like it could be problematic.

the last time the bug happened i was able to restart the delay with `~dirt.orbits[3].globalEffects[0].resume`, indicating that the synth is indeed staying paused when it shouldn't. i tried commenting out the `DetectSilence` line and kept tidaling successfully for about an hour with all delays working fine. not exactly solid evidence yet but i'll test more later!

**Comment by telephon** [comment]
Indeed I suspect that the `DetectSilence` is an old leftover. Can you continue to test it just to be sure? I'll take a look at it if I can find the time.

**Comment by ahihi** [comment]
i will, once i have some time during the weekend!

**Comment by ahihi** [comment]
5-ish more hours of tidaling later, delays are still working great :)

**Comment by telephon** [comment]
Thanks :)!
