### ISSUE TITLE
Should we send RPN Null after NRPN?

### ISSUE THREAD

**Issue by Zalastax** [musikinformatik/SuperDirt#283]
Also at [MIDI NRPN Null Needed? How? @ Tidal club](https://club.tidalcycles.org/t/midi-rpn-null-needed-how/4488).

My synth manual and many other manuals contain a statement like this "Once an NRPN parameters
has been specified, all Data Entry messages received on that channel will modify the value of that parameter. To prevent accidents, it is recomended that you set RPN Null (RPN Number = 7FH/7FH) when you have finished setting the value of the desired parameter."

Jwaldmann didn't face issues when not following this approach, so it might not be needed. But I feel it might anyway be best to follow the recommendation.

Should we do as recommended and follow the approach explained here http://www.philrees.co.uk/nrpnq.htm? It would be simple to add here:
https://github.com/musikinformatik/SuperDirt/blob/f1c4ff923eeabcc8350c45433ef8623d0a624263/classes/DirtEventTypes.sc#L89-L101

**Comment by yaxu** [comment]
I don't know too much about NRPN, and haven't used it much, but yes it sounds like that's worth doing.

**Comment by telephon** [comment]
yes, sounds reasonable. @Zalastax do you want to make a pull request?

**Comment by Zalastax** [comment]
Yes, I will make a pull request @telephon. I expect to be able to do it in a few weeks time.

**Comment by telephon** [comment]
thank you!
