### ISSUE TITLE
Add a simple way to add modules after another specific module

### ISSUE THREAD

**Issue by geikha** [musikinformatik/SuperDirt#297]
It'd be great to have a simpler way to add a module to a specific part of the modules order. The orderModules needs practically all the names to be specified. Maybe a `addModuleAfter` method or an `after` argument for the `addModule` method, where we could simply specify after which module (via name) to insert the new one.

**Comment by telephon** [comment]
Let's say you want to add a module `new` between `bpf` and  `crush`. You can write this as follows:
```supercollider
~dirt.addModule(\new, { ... });
~dirt.orderModules([\bpf, \new]);
```

Does this help?

**Comment by geikha** [comment]
ahhh i think last time i tried it i used strings instead of symbols and that broke the method. so i suspected it to work differently. case closed then! hah
