### ISSUE TITLE
dirt_rms ambiguity. should it be running to not?

### ISSUE THREAD

**Issue by redFrik** [musikinformatik/SuperDirt#299]
a minor issue...

in DirtOrbit the global effect dirt_rms is loaded and set as .alwaysRun_(true).
but initially it won't run because of a missing default for the rmsReplyRate argument.

the missing argument is found in core-synths-global.scd...
```SynthDef("dirt_rms" ++ numChannels, { |gate = 1, dryBus, effectBus, rmsReplyRate, rmsPeakLag, orbitIndex|```

changing it to...
```SynthDef("dirt_rms" ++ numChannels, { |gate = 1, dryBus, effectBus, rmsReplyRate = 20, rmsPeakLag = 3, orbitIndex|```
would make the dirt_rms module run as expected.

thoughts?

**Comment by yaxu** [comment]
Just found this old issue! I don't think rms should be sent without `~dirt.startSendRMS` being run, if that's what you mean?

**Comment by telephon** [comment]
Ah yes, that will be better. Sorry, @redFrik !

**Comment by telephon** [comment]
Actually, looking at the code, I don't see why this shouldn't work already. It would be good if we had a reproducer at hand, then I'd check what is wrong.

**Comment by yaxu** [comment]
Yes it's been working well for me, although I haven't tested it in a little while due to bitrot around [feedforward](https://github.com/yaxu/feedforward)..

**Comment by telephon** [comment]
Just checked,

```



// monitor rms
(
o = OSCFunc({ |msg|
    "peak: %, rms: %".format(msg[3], msg[4]).postln
}, "/rms");

SuperDirt.default = ~dirt;
~dirt.startSendRMS;
)



// test, can you hear
(
(type:\dirt, orbit:0, s: \cr).play;
(type:\dirt, orbit:1, s: \cr, speed:2/5).play;
)

```

It runs while synths are running on the server. I suppose that the semantics of "alwaysRun" is a little brittle: it means always when a synth plays (as opposed to when a parameter is set), not always-always.

**Comment by telephon** [comment]
@redFrik if it doesn't work for you, let me know!

**Comment by redFrik** [comment]
couldn't get your example to run (SuperCollider 3.13.0, SuperDirt dev branch from oct2023), but this example demonstrates my concern...

```supercollider
SuperDirt.start;
s.queryAllNodes; //one dirt_rms2 node per group. all ok - that's how it is set up in DirtOrbit initDefaultGlobalEffects
OSCdef(\rms, {|msg| msg.postln}, "/rms");
~d1 = ~dirt.orbits[0];
~d1.((sound: 'tutorial2', dur: 5, pan: 0.5));

[ /rms, 1002, 0, 0.0, -0.0, 0.0, -0.0 ]
[ /rms, 1002, 0, 0.00034105117083527, nan, 0.00034105117083527, nan ]
```

so i get sent bogus RMS data without calling startSendRMS.

if i _do_ call startSendRMS, stop it and play again, i get the same...
```supercollider
~dirt.startSendRMS;
~dirt.stopSendRMS;
~d1.((sound: 'tutorial2', dur: 5, pan: 0.5));

[ /rms, 1123, 0, 0.0, -0.0, 0.0, -0.0 ]
[ /rms, 1123, 0, 0.00034105117083527, nan, 0.00034105117083527, nan ]
```

but i stopped it!

anyhow, these stray messages are just a minor annoyance, but points to the real problem i'm trying to address in this GitHub issue.

if i go in and set resonable defaults for the dirt_rms SynthDef's rmsReplyRate and rmsPeakLag arguments and turn off alwaysRun in DirtOrbit initDefaultGlobalEffects, then the above example seem to behave like i'd expect.

my analysis is that because RMS synth nodes are always running, it might be more by luck than by design that they do not send back data all the time. the reason it kind of [not] works is because rmsReplyRate defaults to 0.
IMHO, a better way would be to not have the RMS node in the chain until you actually call startSendRMS. and stopSendRMS would free and remove them - just like most other nodes behave in your SuperDirt system.

that'd also clear up the confusion/ambiguity with alwaysRun for RMS synths.

**Comment by telephon** [comment]
The source of the trouble is that the values in `SendPeakRMS` seem to be not modulatable as expected.

```supercollider
OSCdef(\rms, {|msg| msg.postln}, "/rms");
u = { SendPeakRMS.kr(SinOsc.ar, replyRate: \rmsReplyRate.kr(0), peakLag: \rmsPeakLag.kr(0), cmdName:"/rms") }.play;
// ... posts one message. Then try:
u.set(\rmsReplyRate, 2, \peakLag, 2);
// ... nothing.
````

So I need to rethink the global effects a little for this. Maybe I separate the RMS functionality out, it isn't really an effect after all.

**Comment by telephon** [comment]
I am hesitating though to add another logic specially for the RMS stuff.

The problem is that we want to avoid that you get rms messages that are unnecessary (e.g. when not monitoring or when an orbit isn't currently used) – if someone has 100 orbits, this is a lot.

Maybe one could deactivate an effect completely, and then the rms would have a fixed rate, but could be kept in pause mode if not activated.

**Comment by telephon** [comment]
@redFrik could you check #305 if that fixes the issue for you?

**Comment by telephon** [comment]
Testing:

```supercollider


OSCdef(\rms, {|msg| msg.postln}, "/rms");

(type:\dirt, s:\made2).play; // no sending

~dirt.startSendRMS(10);
(type:\dirt, s:\made2).play; // sends


~dirt.startSendRMS(1); // slow it down
(type:\dirt, s:\made2).play; // sends slowly

~dirt.stopSendRMS;
(type:\dirt, s:\made2).play; // no sending
```
