### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by matthewkaney** [musikinformatik/SuperDirt#301]
We're in the process of pushing out a new release of Tidal that incorporates the param from #274 among other things. Is now a good time for a new release of the SuperDirt quark?

**Comment by telephon** [comment]
Yes, of course! Sorry I have missed your message. @yaxu you did the last one – can you do a new one if needed?

**Comment by yaxu** [comment]
@telephon yes happy to do that!

**Comment by yaxu** [comment]
Does this look ready to go? https://github.com/musikinformatik/SuperDirt/releases/edit/untagged-9bf53271a2f1331b0e53

**Comment by ahihi** [comment]
any update on this?

**Comment by telephon** [comment]
@yaxu I hadn't seen your comment from April – I don't think anything has changed after this, so I think this is ready to go.

**Comment by yaxu** [comment]
Well a lot of time passed, but finally I pressed the button.. So sorry for the delay!
