### ISSUE TITLE
`shape` > 1 bug

### ISSUE THREAD

**Issue by bgold-cosmos** [musikinformatik/SuperDirt#48]
Repost from datamads:

Hi everyone

I noticed this problem when messing around with the Shape synth parameter and since I'm new to Tidal I do a lot of stupid shit like for example set the Shape param to 1.5 or something. But if I accidentaly do that, it'll crash the synth totally. 

It's not a huge issue if you know what you're doing but could be a problem live if you by accident or lack of knowledge put a value higher than 1.0 into that one shape parameter. It doesn't do the same for other parameters with a 0.0-1.0 range (for example hcutoff) as far as I can see. 

Here's a simple example that'll make your SuperDirt cry:

```
-- Keep this going so you'll hear when the synth crashes
d2 $ sound "hh*4"

--  Now, start this: it WON't crash the synth
d1 $ sound "bd"
# shape "0.5" 

--  But this will crash the synth
d1 $ sound "bd"
# shape "1.0" 
```

**Comment by bgold-cosmos** [comment]
The issue is that when `shape` is greater than 1 it's supposed to be set to slightly less than one.  But the value currently used is too close, and so what seems to get produced is an inaudible DC offset which blows the limiter for the whole orbit and chokes out other sound.

**Comment by telephon** [comment]
OK; I'll add a `LeakDC`.

**Comment by bgold-cosmos** [comment]
Another possiblity is to change `1.0 - 1e-16` to something like `1.0 - 1e-7`  I worry that 1.0 - 1e-16 is very close to the precision limit of a `double`.

**Comment by telephon** [comment]
note that the scserver runs on 32 bit.

but maybe another shape algorithm sounds better anyway? Normally, I'd use `tanh`, or `Shaper`.

**Comment by bgold-cosmos** [comment]
People get attached to their distortion algorithms :)  The current `shape` is a direct translation of Classic Dirt - except that Classic Dirt limited the parameter to be`min(shape, 0.99)`.  Since that's definitely within floating point precision, maybe it's best to just recreate that?

**Comment by yaxu** [comment]
Actually I only added this limit to classic dirt in the last 9 months, so superdirt is actually closer to 'true' dirt behaviour ;)

**Comment by bgold-cosmos** [comment]
Actually it looks like you added the limit in this commit https://github.com/tidalcycles/Dirt/commit/fda6f753bdbc876f6d95bef3891caebcc470f295
in 2015, but some other change last year (I think with OSC message handling?) broke it, which was then fixed by moving around where it was implemented.

I remember the "moving around fix" being a reimplementation of old behavior because I was the one who did it. :laughing:

**Comment by yaxu** [comment]
Ah! Ok :)

**Comment by telephon** [comment]
c3f5d06291017fafa9758971ef3fe5d80fe4f8ea
