### ISSUE TITLE
amplitudes of global effects should not be global

### ISSUE THREAD

**Issue by bgold-cosmos** [musikinformatik/SuperDirt#59]
To use delay as an example, my understanding of the current behavior is that all sounds get sent into the "dry" bus, which the delay effect processes, and the amount of output into the "wet" bus is scaled by the `delay` parameter.  This means global effects are all-or-nothing in terms of the sounds they affect on each orbit.

While `delaytime` and `delayfeedback` are necessarily global parameters, what I'm proposing is that `delay` itself shouldn't have to be.  In fact, I think most people would like to think of it as basically a "send" amount that can be changed for each sound.  This is how it worked in Classic Dirt, but I think this is worth more than just backwards compatibility, it's a nice feature that people tend to expect based on how DAWs and analog systems work.

As a test case, if you fire up Classic Dirt and send this:
```
c1 $ sound "bd" # delay "1" # delayt "0.1" # delayfb "0.8"

c2 $ sound "~ cp ~ cp" # delay "0"
```
You'll hear that the claps don't interrupt or interefere with the echoing drum.  But in SuperDirt this sounds rather different, because there as soon as the clap hits the delay output is clamped off (because `delay` is global).

I think this can be implemented without too much overhead in SuperDirt by having a "send" bus for each global effect.  Then `dirt_gate` on each sound can use a local `delay` to scale the input into that bus, and finally the global delay unit reads from that bus, does the processing (using the global `delaytime` and `delayfeedback`), and outputs to the wet bus as normal.  The same could be done with `room` for the reverb, and `leslie` for that effect.

My attempts to do this have failed in bizarre ways, however.  It seems I don't understand how to set up the busses, and maybe I'm not thinking about this correctly.  Any suggestions?

**Comment by telephon** [comment]
Yes, you are completely right of course. It's just not there because I left it out for now, and there are some complications one has to carefully consider. 

A basic (event-wise) `inputAmp` for all effects would be very easy to do in two lines sclang and one line in tidal (unless I've forgotten something).

To implement an input amp for *every* effect, however, would require:

1. a separate effect bus for each effect (as you say). For large multichannel setups this means `N x M` channels.
2. a new well defined amplitude name for each effect (this is a matter of discipline)

Because the effects are designed to be extended, you should take the current situation only as a minimal setup: extending it should be easy.

The hardest bit is to specify what effect takes which other effect as input. If this should be specifiable, it gets complicated, because not all combinations are feasible (effects must be an order).


In [Steno](https://github.com/telephon/Steno) I have made a little language for that, and sometimes I thought we should just use that. But on the other hand I try to keep SuperDirt as simple as possible.

**Comment by bgold-cosmos** [comment]
OK, in terms of ordering I was thinking that the global effects are and would be in parallel.  Maybe (probably) I'm misunderstanding how the dry/wet bus interaction works, so maybe if I have another look I'll figure out what I was doing wrong.  But having them in parallel would mirror the common setup of send effects (vs the local effects, which are insert effects).

I think most of the time, with global send effects in parallel, input amplitude ("send amount") is all that is really needed, and I'd use current parameters for that (`delay`, `room`, `leslie`).  Output amp would be `1` by default, but nothing will come out of the effects if nothing is being sent to them.  Output ("return") amount adjustment is redundant unless the effect is nonlinear on the input gain.  Actually, `leslie` does something kind of special there (fades out the dry signal as you turn up the wet), so that might be a case where it would've been better to have explicit input/output gain anyway.

**Comment by telephon** [comment]
You may suddenly clamp down the reverb, for example, no? In particular if you have over-saturated it (it is nonlinear). And we should keep in mind effects that don't exist in the distro, but which people write.

**Comment by telephon** [comment]
I tend not to think in a traditional mixer setup, because I have in mind the abstract routing possibilities of supercollider. The closest to your idea would be to specify the `DirtGlobalEffect` as follows:


`GlobalDirtEffect(name, paramNames, numChannels, inAmpName, outAmpName, outBusName, inBusNames);`


`GlobalDirtEffect(\dirt_reverb, [\size, \dry], \room, \roomOut, \room, [\lesley, \delay])`

This could work. But it does have a bit of extra overhead - every effect out needs a separate synth to do the routing.

It is a bit complicated, though, and I'm not sure if we want this.

**Comment by bgold-cosmos** [comment]
Why the complexity?  Can't the global effects read from their own input bus, do processing, adjust output gain and output to the wetBus?  Why do they need to know about the other effects?
Or are you saying in general they _could_ do this, so why not have the functionality there for people?

**Comment by telephon** [comment]
Most of the complexity is already in this base case. Assuming, e.g. that a lesley is always located outside of any room reverb, you'd still have to specify:

`GlobalDirtEffect(name, paramNames, numChannels, inAmpName, outAmpName)`

The overhead we are creating is just the same (you still need a routing synth per event, or if designed modularly, a routing synth per event and effect).

**Comment by telephon** [comment]
(I'm not against this, just trying to explain)

**Comment by telephon** [comment]
>Or are you saying in general they could do this, so why not have the functionality there for people?

Yes. With the current synths, I think that the order between lesley and room entirely changes the game (the character of the room).

**Comment by bgold-cosmos** [comment]
I think I get it - I was trying (and failing) to use `dirt_gate` as the routing synth.  But even if that worked, adding more global effects would mean modifying `dirt_gate` each time; having it be completely modular means having each send as a local effect.

That gives me another idea towards implementation, I'll see if I can get a working example

**Comment by telephon** [comment]
actually we can just rebuild dirt_gate if necessary

**Comment by telephon** [comment]
… I'm not sure if the overhead is much of adding just a routing synth per effect either. It is more about checking each time whether it is necessary.

But I'm curious, let me know what you find.

**Comment by bgold-cosmos** [comment]
Well, I have an implementation that sort of works, but is glitchy in a strange way that I don't understand.

What I did is to add a "delayBus", making a bunch of changes in SuperDirt.sc to add it beside the dryBus.  I can post a diff but I basically just copy/pasted whatever was going on with the other busses.

Then I made two changes to `dirt_delay`: changed its input from dryBus to delayBus, and removed the output scaling.

Then I made a custom local effect "delay2" (just to make sure I'm avoiding name collision issues).  It's really just a single-line SynthDef: `OffsetOut.ar(delayBus, In.ar(out, ~dirt.numChannels)*delay2);`

When I try the test code, it seems OK for about 4 cycles.  After that, the claps start chopping off the decay tails.  Strangely, when I hush, the delay keeps outputting audio for another 4 cycles.  What's really interesting is that if I change `maxDelayTime` in the delay to 8 seconds, I get the same behavior except now it takes 8 cycles to kick in, and echoes keep happening 8 seconds after `hush`.  (I'm using default `cps 1`)

It seems like somehow there's some issue with a delay buffer filling up?  But I don't understand why a simple bus rearrangement is causing this.

**Comment by bgold-cosmos** [comment]
Posted the branch here in case you want to see what I mean
https://github.com/bgold-cosmos/SuperDirt/tree/delay2

To add the local "send" portion I just evaluate this:
```
(
~dirt.addModule('delay2', {|dirtEvent| dirtEvent.sendSynth("dirt_delay2" ++ ~dirt.numChannels,
	[delay2: ~delay2, out: ~out, delayBus:~delayBus])}, {~delay2.notNil});
SynthDef("dirt_delay2"++~dirt.numChannels, {|out, delay2, delayBus|
	OffsetOut.ar(delayBus, In.ar(out, ~dirt.numChannels)*delay2);
}).add;
)
```
And then from Tidal use `delay2` as a parameter instead of `delay`

**Comment by telephon** [comment]
should be almost it.

**Comment by telephon** [comment]
One thing: you shouldn't use an `OffsetOut` for audio routing, but an `Out`.

**Comment by bgold-cosmos** [comment]
OK, changed that part, but it didn't change the strange glitching after 4s.  I've also tried removing almost everything inessential from the delay SynthDef itself and it hasn't changed the behavior, so it's not a weird interaction with DirtPause or similar.  I don't know if I've done something wrong setting up the bus, or maybe I've managed to discover a strange SuperCollider bug?  I'm on 3.8.0 and the above branch is off of yesterday's SuperDirt `master`

**Comment by telephon** [comment]
Did you have a look where the synths end up in the node order? In the server menu it is `Show Node Tree`, or `Dump Node Tree With Controls`. These kinds of glitches happen sometimes when you read stale data from a bus.

**Comment by telephon** [comment]
You can also just remove `DirtPause`, it is just for efficiency.

**Comment by telephon** [comment]
… and perhaps it is just the delay itself. The `SwitchDelay` comes from sc3-plugins, and they are not always entirely reliable. You could for a test also just use only the "normal" `DelayL` SynthDef.

**Comment by telephon** [comment]
i.e. 
`if(\SwitchDelay.asClass.notNil) {`

rewrite to

`if(false) {`

**Comment by bgold-cosmos** [comment]
Other delay units glitch in different ways, but still don't seem to work.  The Node Tree looks normal to me, but I don't really know what I'm looking for (I'm running with 4 orbits).  I captured this while the bass and clap were playing, the bass is being sent via `delay2`, `delayfeedback` is `2` because this attempt was with `CombN` where I used that parameter for decay time.

```
NODE TREE Group 0
   1 group
      5 group
      1015 dirt_delay2
        dryBus: 30 effectBus: 34 delayBus: 32 gate: 1 delaytime: 0 delayfeedback: 0 delayAmp: 1 lock: 0 cps: 1
      1014 dirt_reverb2
        dryBus: 30 effectBus: 34 gate: 1 room: 0 size: 0.10000000149012 dry: 0
      1013 dirt_leslie2
        dryBus: 30 effectBus: 34 gate: 1 leslie: 0 lrate: 6.6999998092651 lsize: 0.30000001192093
      1012 dirt_monitor2
        dryBus: 30 effectBus: 34 outBus: 0 gate: 1
      4 group
      1011 dirt_delay2
        dryBus: 22 effectBus: 26 delayBus: 24 gate: 1 delaytime: 0 delayfeedback: 0 delayAmp: 1 lock: 0 cps: 1
      1010 dirt_reverb2
        dryBus: 22 effectBus: 26 gate: 1 room: 0 size: 0.10000000149012 dry: 0
      1009 dirt_leslie2
        dryBus: 22 effectBus: 26 gate: 1 leslie: 0 lrate: 6.6999998092651 lsize: 0.30000001192093
      1008 dirt_monitor2
        dryBus: 22 effectBus: 26 outBus: 0 gate: 1
      3 group
      1007 dirt_delay2
        dryBus: 14 effectBus: 18 delayBus: 16 gate: 1 delaytime: 0 delayfeedback: 0 delayAmp: 1 lock: 0 cps: 1
      1006 dirt_reverb2
        dryBus: 14 effectBus: 18 gate: 1 room: 0 size: 0.10000000149012 dry: 0
      1005 dirt_leslie2
        dryBus: 14 effectBus: 18 gate: 1 leslie: 0 lrate: 6.6999998092651 lsize: 0.30000001192093
      1004 dirt_monitor2
        dryBus: 14 effectBus: 18 outBus: 0 gate: 1
      2 group
         1043 group
            -664 dirt_sample_1_2
              out: 4 bufnum: 589 sustain: 0.44512245059013 begin: 0 end: 1 speed: 1 endSpeed: 1 pan: 0 span: 1
            -672 dirt_delay_send2
              out: 4 delay2: 0 delayBus: 8
            -680 dirt_gate2
              out: 6 in: 4 sustain: 0.44512245059013 fadeInTime: 0 fadeTime: 0.0010000000474975 amp: 0.40000000596046 sample: -2080762368 gateSample: 0 cutAll: 0
         1044 group
            -688 dirt_sample_1_2
              out: 4 bufnum: 399 sustain: 0.28367120027542 begin: 0 end: 1 speed: 1 endSpeed: 1 pan: 0 span: 1
            -696 dirt_delay_send2
              out: 4 delay2: 0.5 delayBus: 8
            -704 dirt_gate2
              out: 6 in: 4 sustain: 0.28367120027542 fadeInTime: 0 fadeTime: 0.0010000000474975 amp: 0.40000000596046 sample: 1149979008 gateSample: 0 cutAll: 0
      1003 dirt_delay2
        dryBus: 6 effectBus: 10 delayBus: 8 gate: 1 delaytime: 0.10000000149012 delayfeedback: 2 delayAmp: 0 lock: 0 cps: 1
      1002 dirt_reverb2
        dryBus: 6 effectBus: 10 gate: 1 room: 0 size: 0.10000000149012 dry: 0
      1001 dirt_leslie2
        dryBus: 6 effectBus: 10 gate: 1 leslie: 0 lrate: 6.6999998092651 lsize: 0.30000001192093
      1000 dirt_monitor2
        dryBus: 6 effectBus: 10 outBus: 0 gate: 1
```

**Comment by telephon** [comment]
The structure looks ok to me. Well, some more detective work …

**Comment by bgold-cosmos** [comment]
OK, I have the basic functionality now, using a rather ugly workaround.  And I had to take out the DirtPause, which for some reason wouldn't unpause.  In doing a test just now I also managed to crash SuperCollider, so some issues remain... 

I'm going to see if I can fix things and clean it up, but basic method is:

  * The "send" is done with a local effect that writes into a special bus
  * The rest remains in a global effect which reads the special bus rather than the generic "dry" bus 
  * But the global effect doesn't take Tidal parameters directly as inputs, because nil values would get taken to zero in the SynthDef.  So when building the bundle in `DirtEvent.playSynths` I inserted lines like `~delaytime2 = ~delaytime ? {~delaytime2 ? 0.1};` so that SuperDirt can remember the last "used" value of `delaytime` (this is the ugly part)

**Comment by telephon** [comment]
Thanks a lot for your efforts. I'm sure together we'll find a clean solution for super dirt!

Maybe my questions help?

- what is the difference between the "generic dry bus" and a "special bus"?
- your inserted lines that modify the environment, I am pretty sure, do not what you think. The environment in which `playSynths` is called is local to each and every synth, and nothing in it is remembered. Probably you are seeing some side effects.

But if you feel you've hit a wall, let me know and I'll see if I can come up with a solution. It's not too easy to understand the bus and environment logic in supercollider, and tidal adds quite a bit of non-trivial specification to it.

**Comment by bgold-cosmos** [comment]
Questions are helpful, and I don't think I've quite hit a wall, but I am learning bit by bit how the environment variables get handled.  To answer the questions

  * the goal is to control on an event-by-event basis how much audio gets sent to a global effect, which I think requires at least a "send" bus for the input of each global effect.  The existing dry bus has all sounds already mixed by the gate synth, so I can't use that to selectively echo one sound but not another.
  * as far as I can tell, a global effect Synth reads its input parameters constantly, so if for example `~delaytime` gets set by a particular event, then the global effect will see it.  That's generally fine, but it seems that if `~delaytime` is nil for an event, then the nil is passed into the Synth where the UGen turns it into a zero.  That's not what I want (nor do I want a fixed default), I want the global Synth to remember the last non-nil value.  So that's what I'm trying to do (probably badly) with the environment.

I feel like maybe I've gotten the hang of the Bus situation, but probably still fuzzy on the environment variables.  Particularly how SuperDirt passes them along and how that works for global effects where many Events might happen in a single control cycle.

Now that I'm thinking about all this, maybe it would be cleaner if global parameters each had their own control bus?  Those explicitly don't change unless they receive new input.

**Comment by telephon** [comment]
In general, this sounds very good.

- yes, for each global synth that you want to separate off, you need a event-local synth as a send. One can add these either as modules, like local effects, or build them into the `GlobalDirtEffect` class.

- if you want to set defaults that make a 'backdrop', this is normally added to the `DirtOrbit`'s `defaultParentEvent`. You could add them there. But because we want the system to be easy to maintain, a `GlobalDirtEffect` would better keep defaults internal. It's basically all in the `set` method, but it is delicate. However:

>Now that I'm thinking about all this, maybe it would be cleaner if global parameters each had their own control bus?

It isn't cleaner, but a bit easier maybe. A good idea, but take a look at what the `set` method does. The behaviour could probably be changed, but this is where it currently happens.

More generally:
In SuperDirt 1.0-dev there are three events (aka environments) involved: 

1. the one that is global to an orbit, 
2. the one that is stored in the dirt sound library for each sound, 
3. and the one that is created from the tidal parameters for each "grain". 

They override each other in that sequence (via `parent`). So when you write `~x = ~x + 1` and `~x` is defined in the parent, the parent isn't changed, but the so called `currentEnvironment`. This kind of dynamic scope is really elegant, but you have to be aware of what you are doing sometimes.

**Comment by bgold-cosmos** [comment]
Will continue discussion in #75
