### ISSUE TITLE
Failing multichannel output

### ISSUE THREAD

**Issue by bgold-cosmos** [musikinformatik/SuperDirt#64]
I believe this may be related to a SuperCollider issue (see below) but I'd like to make an issue here in case I'm wrong or there's a workaround.

The problem arises when trying to use more than 2 output channels while also assigning different orbits to different channels.  This necessitates the "long" startup method, something like (as a close-to-minimal example):
```
s.options.memSize = 8192 * 64; // increase this if you get "alloc failed" messages
s.options.numOutputBusChannels = 8;
s.waitForBoot {
    ~dirt = SuperDirt(8, s); 
    ~dirt.loadSoundFiles("/Users/bgold/tidal/samples/*"); // load samples (path can be passed in)
    s.sync; // wait for samples to be read
    ~dirt.start(57120, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]);   // start listening on port 57120
};
);
```
This however results in a flood of messages: `ERROR: Meta_Bus:audio: failed to get an audio bus allocated. numChannels: 8 server: localhost`

This looks a lot like this issue: https://github.com/supercollider/supercollider/issues/2758 which in turn I _think_ was fixed by https://github.com/supercollider/supercollider/pull/2761 somewhat after the 3.8.0 release.  So this may resolve itself with the next SuperCollider release, but I haven't tested yet (by compiling `devel` from scratch), and meanwhile this is a pretty serious issue for anyone trying to use multichannel SuperDirt.

**Comment by telephon** [comment]
Yes, it'll be fixed by the coming release. But you can also adjust yourself:

`s.options.numAudioBusChannels = 2048`

**Comment by telephon** [comment]
Btw you can write `~dirt.start(57120, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]); `

as `~dirt.start(57120, (0..15)); `

**Comment by telephon** [comment]
Note that your startup will create 16 orbits of 8 channels each, and each starting to play from another bus:

```supercollider
(0..15) +.t (0..7) do: _.postln 

// these are the output channels of your 16 orbits à 8 channels
[ 0, 1, 2, 3, 4, 5, 6, 7 ]
[ 1, 2, 3, 4, 5, 6, 7, 8 ]
[ 2, 3, 4, 5, 6, 7, 8, 9 ]
[ 3, 4, 5, 6, 7, 8, 9, 10 ]
[ 4, 5, 6, 7, 8, 9, 10, 11 ]
[ 5, 6, 7, 8, 9, 10, 11, 12 ]
[ 6, 7, 8, 9, 10, 11, 12, 13 ]
[ 7, 8, 9, 10, 11, 12, 13, 14 ]
[ 8, 9, 10, 11, 12, 13, 14, 15 ]
[ 9, 10, 11, 12, 13, 14, 15, 16 ]
[ 10, 11, 12, 13, 14, 15, 16, 17 ]
[ 11, 12, 13, 14, 15, 16, 17, 18 ]
[ 12, 13, 14, 15, 16, 17, 18, 19 ]
[ 13, 14, 15, 16, 17, 18, 19, 20 ]
[ 14, 15, 16, 17, 18, 19, 20, 21 ]
[ 15, 16, 17, 18, 19, 20, 21, 22 ]
```

**Comment by telephon** [comment]
@bgold-cosmos is this solved?

**Comment by bgold-cosmos** [comment]
Appears so!
