### ISSUE TITLE
Disable `sclang` test code by default

### ISSUE THREAD

**Issue by jarmitage** [musikinformatik/SuperDirt#65]
https://github.com/musikinformatik/SuperDirt/blob/6818f0642f6107be45814489c37d10a481d29f17/superdirt_startup.scd#L23

On some Tidal workshop installs this test code had to be commented out for SuperDirt to work, which means if we want to advise people to use this default setup we also need to tell them to comment out this block.

**Comment by telephon** [comment]
why did it have to be commented out? was there a specific error message you could post ?

**Comment by jarmitage** [comment]
It was in a middle of a workshop sorry. But the steps were;

- Start as normal using `SuperDirt.start` - success
- Start using the default SuperDirt `startup.scd` - fail
- Comment out test lines in SuperDirt `startup.scd` - success

**Comment by telephon** [comment]
if you come across it again, could you pleas post the error here? I haven't been able to reproduce it here.

**Comment by jarmitage** [comment]
Yes I will, let's close for now
