### ISSUE TITLE
Support non-sclang SynthDefs

### ISSUE THREAD

**Issue by vivid-synth** [musikinformatik/SuperDirt#66]
https://github.com/vivid-synth/vivid/issues/3 

SuperDirt lets you play SynthDefs in addition to samples, but it currently breaks when you try and play samples that haven't been defined in ```sclang```.

**Comment by telephon** [comment]
>breaks when you try and play samples that haven't been defined in sclang.

Sure you don't mean _synths_  that haven't been defined in sclang?

**Comment by vivid-synth** [comment]
Yes, apologies - breaks when you try and play SynthDefs defined outside of sclang

**Comment by telephon** [comment]
Does the workaround https://github.com/vivid-synth/vivid/issues/3  count as a fix?

**Comment by vivid-synth** [comment]
What I'd like to be able to do (and it used to be possible) is to define synthdefs on-the-fly (in Haskell), and then use them with Tidal. Currently the workaround lets us define dummy synthdefs in sclang and then redefine them in Haskell, but it would be great to skip the middle step.

**Comment by telephon** [comment]
do you use a standart set of parameters ? the only reason we need the dummy is that haskell doesn't pass information to sclang about the parameters a synthdef uses.

**Comment by vivid-synth** [comment]
@telephon we could; maybe the standard set of `amp`/`gain`, `pan`, etc.?

**Comment by telephon** [comment]
for a missing sample or synthdef, you'll get a less specific error then ( synthdef not found ). If that is ok ...

**Comment by vivid-synth** [comment]
I think that's fine!
