### ISSUE TITLE
dynamic used some sc buffer 

### ISSUE THREAD

**Issue by lisongx** [musikinformatik/SuperDirt#67]
Hi, 
Just some idea came up recently, I want use some live recorded sc buffer in tidal.

For example if have a sc Buffer live recorded some stuff,  like `b1 = Buffer()`, can I use this buffer directly in tidal? (maybe with some kind of registration on the dirt sound lib itself?)

```
~dirt.addSoundBuffer("buffer", b1)
```

and then I can 

```
d1 $ sound "buffer * 3"
```

Not sure it's already possible or it's something will added soon, thanks!

**Comment by telephon** [comment]
good idea! it exists, you've almost guessed the name:

`~dirt.soundLibrary.addBuffer(\buffer, b1);`

you need `SuperDirt 1.0-dev` for this.

**Comment by lisongx** [comment]
@telephon 
Hi Julian, 
it's very happy to know it's already implemented in the future version. I'll try the `1.0-dev`, thanks so much
