### ISSUE TITLE
Cutoff behavior with negative numbers

### ISSUE THREAD

**Issue by echophon** [musikinformatik/SuperDirt#70]
I accidentally sent some negative numbers to `cutoff`.  The behavior at values around -50 or less clip in an abrasive way & might be bypassing the built-in limiter?  The clipping gets worse the more negative you go.

**play at the below example at low volumes only!**
Example: 
`d1 $ sound (samples "amencutup*8" $ run "8") # cutoff "<5000 2000 0 -10 -20 -50 -100>"`

**Comment by telephon** [comment]
thanks, this should fix it.
