### ISSUE TITLE
Long samples and synths (not) being freed after envelope end

### ISSUE THREAD

**Issue by madskjeldgaard** [musikinformatik/SuperDirt#71]
I've had some issues with superdirt when using long samples in tidal in conjunction with the envelope. Looking at the plot tree it seems it doesn't free the synth even after the envelope has ended (tested with `#attack 0.5 # release 1` so quite modest envelope) which results in a buildup of cpu usage. 

After looking at the source code for a while and trying different hacks I solved it by adding a `doneAction: 14` to the `EnvGen.ar` ugen as is in the superdirt cut group ugen. 

Posting my solution here because I suck at using github and don't know where else to put it, haha. 

```
/****** FIXES PROBLEMS WITH NO RELEASE OF SYNTH GROUP ON LONG SAMPLES ****/ 
SynthDef("dirt_envelope" ++ numChannels, { |out, attack = 0, hold = 0, release = inf |
        var signal = In.ar(out, numChannels);
        signal = signal * EnvGen.ar(Env.linen(attack, hold, release, 1, -3), doneAction:14) // Added: doneAction: 14; // doneAction: 14 added to make sure synth is freed after envelope is done
        ReplaceOut.ar(out, signal);
    }, [\ir, \ir, \ir, \ir]).add;
```

**Comment by bgold-cosmos** [comment]
OK, doneActions are a little bit voodoo to me but that seems reasonable, I'll test it out.  It's definitely true that the current behavior is to keep all the SynthDefs going until the sample is "done" regardless of envelope.

**Comment by telephon** [comment]
Yes, sure - envelope is only an effect. It doesn't change your sound (and shouldn't). If you want to shorten your playback, you could use `# sustain`
