### ISSUE TITLE
Routing external input through SuperDirt

### ISSUE THREAD

**Issue by cannc4** [musikinformatik/SuperDirt#73]
Hey, 

Is it possible to route hardware inputs through SuperDirt ecosystem? It would be interesting to use it alongside with superdirt-midi and apply various orbit-wise effects to midi patterns/channels 

```
~d5 = ~dirt.orbits[4];
SynthDef(\ucx1, { arg in=0, amp = 1, out = ~d5.dryBus;
    var input;
    input = SoundIn.ar(in,2);
    input = input  * amp;
    OffsetOut.ar(out, DirtPan.ar(input, ~dirt.numChannels,amp));
}).play;
 ```
I also tried `.outBus` and didn't seem to work. any tips?

cheers!
C

**Comment by telephon** [comment]
sure, there is already a synth that does it, called `in`, another one `inr` (pitch shifted). Take a look at the `synths/default-synth.scd` file, if you want to make variants.

Does that help?

**Comment by cannc4** [comment]
Ah well, how would I instantiate the synth without having to type anything in Tidal? 
I am guessing I'd still need to use the getter function for sd orbit?

**Comment by telephon** [comment]
hm, I think I don't understand yet. Do you want to constantly route the input through, that is globally into an orbit?

**Comment by cannc4** [comment]
Yes, that would be correct. `SoundIn.ar([1,2])`  -> dirt orbit

**Comment by telephon** [comment]
check `hacks/adding-global-effects.scd`, there is basically the full explanation. 

You basically need a synth like this:
```
(
var numChannels = ~dirt.numChannels;
(1..SuperDirt.maxSampleNumChannels).do { |numChannels|
	SynthDef("dirt_global_in" ++ numChannels, { |dryBus, effectBus, gate = 1, dry = 0|
		var signal = SoundIn.ar([0, 1]).wrapExtend(numChannels);
		XOut.ar(effectBus, 1 - dry, signal)
	}).add;
};
)
```

let me know if you need more help.

**Comment by cannc4** [comment]
Hey, I did some initial tests and got `wrapExtend(numChannels)` error. However, managed to get it working without it. thanks. 
Another somewhat related question is, I'd like to use SuperDirt alongside with another framework I am working on so what I'd like to do is to target dirt orbit's within that other framework and get the audio out from SuperDirt orbits.

A pseudocode example would be something like: `Out.ar(nonsuperdirt_audio, ~d1.dryBus.index)`

**Comment by telephon** [comment]
`~dirt.orbits[0].outBus = your bus index you want to send audio to`

**Comment by telephon** [comment]
>Hey, I did some initial tests and got `wrapExtend(numChannels)` error. However, managed to get it working without it

what was the error?

**Comment by cannc4** [comment]
`ERROR: Message 'wrapExtend' not understood.` 

if I give `~dirt.orbits[0].outBus` as an argument to a synth's out, it should just work right?
That didn't seem to have any effect when I tried it at first so thought I'd ask it here.

**Comment by telephon** [comment]
no, don't worry about the synth. in your dirt startup you can specify the out bus.

**Comment by telephon** [comment]
about the error: what was the receiver?
