### ISSUE TITLE
SuperDirt temporarily breaks on silence

### ISSUE THREAD

**Issue by yaxu** [musikinformatik/SuperDirt#83]
If I run something like this: `d1 $ sound "bd"`

then stop it for a few seconds:  `d1 silence`

then start it again: `d1 $ sound "bd"`

Nothing happens.. until about 10 or so seconds later there are glitches and it comes back again.

This problem appears to be local to the 'orbit'. As long as a sound is keeping a particular orbit 'alive' it's ok.

I noticed this a few days ago but assumed it was a hardware issue with the backup laptop I was using, but now several others have experienced the same kind of behaviour.

This looks related: https://github.com/musikinformatik/SuperDirt/commit/7b5d7000a85cc56b69059449105da51973e0c910

**Comment by jarmitage** [comment]
I had to go back to https://github.com/musikinformatik/SuperDirt/commit/7c7dcaaafe861550ee546a93e6c226afda296b18 for things to work again

edit: currently on SC 3.8.0

edit2: can confirm this issue still present on SC 3.9.3

**Comment by yaxu** [comment]
I'm on supercollider 3.7.0, by the way.

**Comment by bgold-cosmos** [comment]
I have noticed this on supercollider 3.9.3 as well.
SuperDirt appears to be receiving the messages from Tidal, as "dump OSC" will show all of them.  It just doesn't seem to do anything with them, not even "late".  Sending messages more quickly might bring things back sooner, but I haven't verified.

**Comment by bgold-cosmos** [comment]
Commenting out the DirtPause line in dirt_monitor seems to fix it.  I'll submit a PR

**Comment by jarmitage** [comment]
Said PR: https://github.com/musikinformatik/SuperDirt/pull/84

**Comment by telephon** [comment]
Should be fixed, feel free to reopen if it persists.
