### ISSUE TITLE
Accessing to a single SuperDirt instance/node 

### ISSUE THREAD

**Issue by cannc4** [musikinformatik/SuperDirt#87]
The idea is to control a synth from SuperCollider while using Tidal.  
Usually in SC, I store Synth_ids to be able to change the parameters on the fly without having to re-allocate the voice.  e.g `syntharray[0].set(\coarse, 2);` 

Is there any way to access the synth_ids within the sclang? 
If I can access globaleffect_ids, that would be super useful too.

**Comment by telephon** [comment]
There is no place where dirt stores any synth ids (for efficiency), apart from the global effects ones.

But, maybe this is what you want:

- set the synth parameters of a dirt orbit by `~dirt.orbits[0].set(\paramname, param, \paramname2, param2 ...)`
- set the parameters of global effects of an orbit by `~dirt.orbits[0].setGlobalEffects(\paramname, param, \paramname2, param2 ...)`.

**Comment by cannc4** [comment]
That makes sense.
Will definitely explore `.setGlobalEffects` 
What's the scope of the `~dirt.orbits[0].set`? All the synth params going through the specified orbit?

**Comment by telephon** [comment]
>What's the scope of the ~dirt.orbits[0].set? All the synth params going through the specified orbit?

yes. They will be overridden from tidal, if you send them. You can use functions as parameter value if you want something to be called at each event.

**Comment by telephon** [comment]
(just closed because this is not really an issue)
