### ISSUE TITLE
defining new synths with different envelope behavior

### ISSUE THREAD

**Issue by victor-shepardson** [musikinformatik/SuperDirt#89]
Suppose you want to define an instrument with built-in ADSR envelopes (as opposed to attack-hold-release envelope effect existing in SuperDirt). notes from this instrument should release when the sound ends. i.e. using `legato` of 1, each note releases as the next one starts.

It seems that when a sound ends according to its sustain, legato and cut parameters, it is immediately cut off with a very short fade and the synth destroyed, making such behavior impossible.

But sustain could be extended by a new release-time parameter. It seems to work with the following change to `calcRange` in DirtEvent.sc:
```
// sustain = ~sustain ?? { if(~legato.notNil) { ~delta * ~legato } { unitDuration } };
unitDuration= if(~legato.notNil) { ~delta * ~legato } { unitDuration };
unitDuration= if(~rel.notNil) { unitDuration+~rel } { unitDuration };
sustain = ~sustain ?? {unitDuration};
```
where `rel` is the new release-time parameter.

Now you can write a synth like:
```
SynthDef(\adsrsynth, { |out, att=0, dec=0, sus=0.5, rel=0, curve=0, sustain=1, pan, freq|
    var fadein = 0.001, fadeout = 0.003;
    var begin = Impulse.ar(0);
    var cut_env = EnvGen.ar(
        Env.asr(fadein, 1, fadeout, 1, -3),
        Trig.ar(begin, sustain-fadeout), doneAction:2);
    var sound_env = EnvGen.ar(
        Env.adsr(att, dec, sus, rel, 1, curve),
        Trig.ar(begin, sustain-rel));
    var sound = ...;
    OffsetOut.ar(out, DirtPan.ar(sound, ~dirt.numChannels, pan, cut_env))
}).add;
```

Am I missing some way to do this _without_ altering SuperDirt? Or would there be interest in making a built-in parameter like this?

**Comment by telephon** [comment]
There is a clear meaning of `legato` and `sustain`: both specify the total duration of a sound. If you want the sound to release within that period, you have to divide that time (or subtract something from it) and use the rest as a release.

Something like for example: `EnvGen.kr(Env([0, 1, 1, 0], [0.1, 0.4, 0.5]), timeScale: sustain)` 

Don't use gated envelopes, they won't work properly for this purpose. Only fixed time envelopes work. This is not an issue because we know the sustain time when the synth starts.

This you can do completely in your synthdef - only `sustain` matters here, because `legato`is converted to `sustain`. If there are extra parameters that you want for specifying these segments, you can define them in tidal and send them over.

Does this help?

**Comment by victor-shepardson** [comment]
I think I understood all that, but what about envelopes which follow the structure of a pattern via `cut` or `legato`? As far as I can tell there is no way to do this currently in the general case. you'd have to time out every note by hand to construct the corresponding envelope parameters, which defeats the purpose of `cut` and `legato`, no?

If you could this in Tidal: `pattern # legato 1 |+| sustain 0.3 # rel 0.3` it would solve the problem. But that doesn't work because either legato or sustain overrides the other, right? So there would have to be a new `postSustain` or `coda` or something which would be additive with the duration determined together by sustain, cut and legato: `pattern # legato 1 # coda 0.3 # rel 0.3`.

**Comment by telephon** [comment]
>As far as I can tell there is no way to do this currently in the general case.

I am sorry, I don't understand what you are trying to achieve. Can you explain in an example how exactly the synths should behave?

**Comment by victor-shepardson** [comment]
I'm writing synths with envelopes that _start_ the release phase when the sound is cut off by another sound due to `cut` or `legato 1`. The release time is specifiable in seconds, not as a fraction of the note duration.

I believe the example SynthDef in my original post is correct. Gate envelopes should work as long the gate is open for less than `sustain`, right?

**Comment by telephon** [comment]
I see, I think you want to use the `delta` parameter which tidal sends. `delta` is the inter-onset time between subsequent synths. 

Your envelope might then (schematically) look like this:

```supercollider
SynthDef(\x, { |delta, sustain | // and all the other args
var t1, t2, t3;
t1 = 0.2 * delta;
t2 = 0.8 * delta;
t3 = sustain - t1 - t2;

Env([0, 1, 1, 0], [t1, r2, t3])
``` 

>I believe the example SynthDef in my original post is correct. Gate envelopes should work as long the gate is open for less than sustain, right?

Yes, should be fine. The only thing is that it won't do what you are trying to do because you are not using the information that is needed (`delta`). Sorry, you can't know this, it's undocumented!

You could use `delta` in your SynthDef above, I believe. Just combine it with `sustain` to get the total synth durations.

**Comment by victor-shepardson** [comment]
Sorry to forget about this for three months. Thank you! `delta` is good to know about. 

If I understand correctly, you show how to write a synth which releases when the next note begins. But if using `legato > 1` to set the sustain,  the release time will be proportional to duration. 

To get a constant release time, one could define a `rel` parameter (_without_ needing to monkey in SuperDirt internals) as the _maximum_ release time in seconds, taking effect when `delta+rel < sustain`. And to keep using `legato` (so it determines `sustain-rel` rather than `sustain`) one can define a new pseudo-legato `leg` to use instead.

So the synth would be:
```
SynthDef(\adsrsynth, { |out, att=0, dec=0, sus=0.5, rel=0, curve=0, leg=1, sustain, pan, freq|
    var fadein = 0.001, fadeout = 0.003;
    var begin = Impulse.ar(0);
    var cut_env = EnvGen.ar(
        Env.asr(fadein, 1, fadeout, -3),
        Trig.ar(begin, delta*leg+rel-fadeout, doneAction:2);
    var sound_env = EnvGen.ar(
        Env.adsr(att, dec, sus, rel, 1, curve),
        Trig.ar(begin, delta*leg));
    var sound = ...;
	OffsetOut.ar(out, DirtPan.ar(sound, ~dirt.numChannels, pan, cut_env))
})
```

So this gets the job done without changing SuperDirt, it's just a little awkward to have to manage that condition (`delta*leg+rel < sustain`) on the Tidal side. I still see a niche for an additive sustain parameter or a change in behavior to make `sustain` and `legato` additive.

**Comment by telephon** [comment]
Yes, as long as the effective sound duration is equal to the `sustain` parameter, you are entirely free to do what you want. If it is larger, your synth is going to be cut off at sustain.

>I still see a niche for an additive sustain parameter or a change in behavior to make sustain and legato additive.

I don't understand, sorry?

**Comment by victor-shepardson** [comment]
Sorry it's confusing to talk about `sustain` as both a Tidal parameter and a value computed in `DirtEvent`

`sustain` (in SuperDirt) can be set as a constant time in seconds via `sustain` (Tidal), or as a fraction of `delta`, via `legato`. But what if I want `sustain` to be a fraction of `delta` plus a constant amount?

For example, say I have a pattern of mixed note length. I want to cut each note off slightly before the next one starts for a punchier sound . I could use `# legato 0.9`, but it would leave too long of a gap after longer notes and too short of a gap after brief notes. I'd like to do something like `# legato 1 # sustain (-0.03)`. But that doesn't work because `legato` or `sustain` overrides the other, instead of being additive.

If it did work, it would solve my original problem too, without needing to use a bogus large value of `sustain` and fake `leg` parameter -- I would just set my release time to the same as `sustain` and use `legato` as normal.

**Comment by telephon** [comment]
>Sorry it's confusing to talk about `sustain` as both a Tidal parameter and a value computed in `DirtEvent`

If you define `sustain` explicitly in tidal (e.g.`# sustain "1 0.5"`) you are just overriding the default calculation that happens in superdirt. 

>But what if I want `sustain` to be a fraction of `delta` plus a constant amount?

Then you either do this calculation in tidal, or, if it is dependent on the synth, you can do it in superdirt:

```supercollider
~dirt.soundLibrary.addSynth(\yoursynthname, (legato: 1, additionalAmount: 0, sustain: { ~delta * ~legato.value + ~additionalAmount }));
```
(untested)

You can then add `additionalAmount` or whatever variable name you want to use, to tidal, and pass that. If you have that parameter in your SynthDef, it'll be also accessible there for using it in the envelope shape.

Such a parameter is a good idea, we could add it to SuperDirt later.

**Comment by victor-shepardson** [comment]
Ah ok that works after switching to 1.0-dev. Need to include the `instrument` field it looks like. This does everything I wanted: `legato` works normally, `rel` given in seconds extends the synth duration, no extra parameters or hacks on SuperDirt.
```supercollider
SynthDef(\adsrsynth, { |out, att=0, dec=0, sus=0.5, rel=0, curve=0, sustain, pan, freq|
    var begin = Impulse.ar(0);
    var env = EnvGen.ar(
        Env.adsr(att, dec, sus, rel, 1, curve),
        Trig.ar(begin, sustain-rel));
    var sound = ...*env;
    OffsetOut.ar(out, DirtPan.ar(sound, ~dirt.numChannels, pan))
}).add;
~dirt.soundLibrary.addSynth(\adsrsynth, 
    (instrument:\adsrsynth, att:0, dec:0, rel:0, legato:1, sustain: {
        (~delta*~legato).max(~att+~dec)+~rel}));
```
thanks!
