### ISSUE TITLE
develop branch now default?

### ISSUE THREAD

**Issue by yaxu** [musikinformatik/SuperDirt#90]
I noticed a workshop attendee was running the 'develop' branch, without intending to. They were happy to have superdirt midi, but is it intended that the develop branch is installed by default?

**Comment by telephon** [comment]
Yes, I understood that you planned to make the development branch the default branch, so I followed that. If we need releases, we would have to add tags to the branch. Or have I misunderstood?

**Comment by yaxu** [comment]
Righto, so we get people to install a tagged release rather than the default branch? How is that done?

**Comment by telephon** [comment]
I haven't tagged a release yet. Not sure where to make a mark right now, since all changes were essentially gradual improvements (apart from the older larger steps between master and 1.0-dev). I'm unsure what is best.

**Comment by yaxu** [comment]
I've been liberally tagging releases, just as a way of getting people up to date with a known version, hope that's OK.
