### ISSUE TITLE
Conditionals in SuperDirt

### ISSUE THREAD

**Issue by cannc4** [musikinformatik/SuperDirt#95]
Hi all,

As there's a refactor going on for Tidal, I thought it would be the right time to share this idea I've been experimenting with Tidal/SuperDirt/JS combo.

This allows to me receive Tidal parameters via SuperDirt to be forwarded to the `stdout`

```
f = { |msg, time, addr|
			if(msg[0] == '/play2') {
				"time: % sender: %\nmessage: %\n".postf(time, addr, msg);
			}
		};
		thisProcess.addOSCRecvFunc(f);
```

then I can parse the code do conditional triggers from Tidal like
```
let (trigLookup,trigLookup_p)  = pS "trigLookup" (Nothing)
    (trigEvery,trigEvery_p)  = pF "trigEvery" (Nothing)
    (trigSound,trigSound_p)  = pS "trigSound" (Nothing) 

d1 $ note "0 1" #s "synth" #trigLookup "0" #trigEvery "7" #trigSound  (pure "(type:\\dirt, orbit:0, s: \\303bass).play;")

```
then I can simply compile `trigSound` param within SuperColliderJS's sclang. 

I find this to be a quite funky feature so I wonder if this can be supported within the SuperDirt to avoid any redundant latency caused by parsing and moving messages around

**Comment by telephon** [comment]
you can easily add an event that does whatever you want:

```supercollider
~dirt.soundLibrary.addSynth(\specialSynth, (play: { here goes your code }));
```

maybe that would be something to try?

**Comment by telephon** [comment]
@cannc4 did this help?
