### ISSUE TITLE
Note-066 in the xx folder has silence at the begining of the sample

### ISSUE THREAD

**Issue by ArthOrban** [musikinformatik/SuperDirt#96]
I think I fixed it, but github doesn't let me upload wav. Warning I fixed it using audacity, so akin to using a sledgehammer. maybe someone who is more familiar can have a look.

[note-066a.wav.txt](https://github.com/musikinformatik/SuperDirt/files/2568381/note-066a.wav.txt)

**Comment by yaxu** [comment]
Thanks @ArthOrban, I'm travelling atm but will take a look when I'm back if someone else doesn't jump in. I ripped these samples from my jx1080 synth using an automatic script to remove silence from the start, it obviously missed a bit here..

**Comment by yaxu** [comment]
Sorry, forgot about this! But actually I think xx isn't part of the standard dirt-samples pack. I'm not sure about adding it, as dirt-samples is already a big download

**Comment by ArthOrban** [comment]
My mistake, again. The samples came from your Spicule repo, instead of this one...
So I guess I learned a valuable lesson about using github the proper way.
