### ISSUE TITLE
ERROR: class not defined when loading superdirt_start.scd

### ISSUE THREAD

**Issue by jwaldmann** [musikinformatik/SuperDirt#97]
Hi. I am running
```
sclang superdirt_startup.scd
```
I expect that `sc` starts, so I can use tidal. But what actually happens is this
```
compiling class library...
Qt: Session management error: Could not open network socket
	Found 845 primitives.
	Compiling directory '/opt/supercollider/3.10.0/share/SuperCollider/SCClassLibrary'
	Compiling directory '/opt/supercollider/3.10.0/share/SuperCollider/Extensions'
	Compiling directory '/home/waldmann/.local/share/SuperCollider/Extensions'
	Compiling directory '/home/waldmann/.local/share/SuperCollider/downloaded-quarks/Vowel'
	numentries = 1257911 / 18817904 = 0.067
	5624 method selectors, 3346 classes
	method table size 20374728 bytes, big table size 150543232
	Number of Symbols 14675
	Byte Code Size 433421
	compiled 544 files in 1.42 seconds

Info: 4 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.01 seconds


*** Welcome to SuperCollider 3.10.0. *** For help type ctrl-c ctrl-h (Emacs) or :SChelp (vim) or ctrl-U (sced/gedit).
ERROR: Class not defined.
  in interpreted text
  line 17 char 18:

  	~dirt = SuperDirt(2, s); // two output channels, increase if you want to pan across more channels
                    
  	~dirt.loadSoundFiles;   // load samples (path containing a wildcard can be passed in)
-----------------------------------
```
Is the "Qt session management error" actually an error?  I compiled sc without QT, which makes the message vanish, but does not change what follows.

**Comment by telephon** [comment]
So everything works, you just get this error message? (`Qt: Session management error: Could not open network socket`).

**Comment by jwaldmann** [comment]
No, nothing works. I am getting "ERROR: Class not defined", and then tidal will complain that no dirt is running.

**Comment by yaxu** [comment]
Does `/home/waldmann/.local/share/SuperCollider/downloaded-quarks/SuperDirt` exist and if so does it contain the superdirt library? From that output I can see Vowel is being loaded but not SuperDirt..

**Comment by jwaldmann** [comment]
Problem solved. I found that "/home/waldmann/.config/SuperCollider/sclang_conf.yaml" was referencing only Vowel, but not SuperDirt. 

I was using "strace" to find what files are read. I am shocked at how many hidden config and data files are apparently being used by supercollider.

**Comment by telephon** [comment]
>I was using "strace" to find what files are read. I am shocked at how many hidden config and data files are apparently being used by supercollider.

Can you give some details which shocked you and why?

**Comment by jwaldmann** [comment]
Not specific files, but their sheer number.

Run `strace sclang`  and see for yourself. I count 3952 lines of the form 
```
openat(AT_FDCWD, " .. some-file-name ...", O_RDONLY ... )  = ....
```
Of these, 2678 are successful. Of course, some are by the OS's DLL loader (for finding/opening .so files), 
some are by Qt for finding fonts (useless - as I am not running the GUI), the rest is by SC.
Of these, most are for reading samples and synthdefs.

It does seem that .config/SuperCollider/sclang_conf.yaml is SC's only config file under $HOME.
But I am not seeing where this is documented at http://doc.sccode.org/ .

In days of old, each program had a man page, and each man page had a FILES section that would clearly show what files are being read at startup, so you know where to look for (mis)configuration.

**Comment by yaxu** [comment]
Possibly not the right place to raise this, but I do often see problems with updating the superdirt quark. I tell people to update superdirt via `Quarks.gui`, they do so but it seems the quark isn't actually updated.. So I then tell them to delete the folder and replace it with a zip downloaded from github. Is this likely to be a superdirt-specific problem?
