### ISSUE TITLE
Tempo synced delay

### ISSUE THREAD

**Issue by yaxu** [musikinformatik/SuperDirt#99]
Would it be possible/a good idea to have an option where delaytime is relative to cps?

**Comment by telephon** [comment]
The `\lock` parameter of the delay does that. IIRC, it's just setting `lock = 1`.

**Comment by telephon** [comment]
@yaxu does that work for you?

**Comment by yaxu** [comment]
Yes, thanks!
```
d1 $ sound "bd" # delay 0.8 # delaytime 0.125 # delayfb 0.7 # lock 1
```
